### ISSUE TITLE
Shortcuts bar hide option does not work properly with external keyboards in IOS14

### ISSUE THREAD

**Issue by darkisildur** [ish-app/ish#912] opened 2020-09-25 06:37 UTC
Hi, 

I have enabled the option “Hide with External Keyboard” for Extra Keys tool bar, under External Keyboard settings. However, when you come back from the settings pop up to the cli, the bar is continuously showing up and hiding as you type using the external keyboard. If I switch between apps and get back to iSH, the bar does not show up anymore. But if I close the app and reopen it, the issue comes back and I have to switch between apps as a workaround. I am running IOS14 on an IPad Pro 2018. The shortcuts bar is enabled system wide for other apps like mail or notes. This was not happening on IOS13. 

Thanks!

**Comment by tbodt** [comment] 2020-10-25 02:19
Seems like a duplicate of #906

**Closed by tbodt** 2020-10-25 02:19 UTC
