### ISSUE TITLE
MMS support

### ISSUE THREAD

**Issue by DG1038286** [ish-app/ish#682] opened 2020-04-16 12:07 UTC
I’m trying to run syncthing through the apk package available on alpine Linux. It downloads and installs fine but when I try to start the program, it gives me the message: “This program can only be run on processors with MMX support.”

**Comment by filfat** [comment] 2020-04-16 13:23
See #57

**Comment by tbodt** [comment] 2020-04-17 00:43
Duplicate of #57

**Closed by tbodt** 2020-04-17 00:43 UTC
