### ISSUE TITLE
Compiling OpenSSH crashes iSH

### ISSUE THREAD

**Issue by kouwei32** [ish-app/ish#1747] opened 2022-03-04 05:42 UTC
1. Clone `openssh-portable` 8.9 from Github or mirror
2. If applicable, install dependencies (libedit-dev etc.)
3. Generate config file (`autoreconf`)
4. Run config (`./configure —with-libedit`)
5. Observe hard-crash after some checks

```
{"app_name":"iSH","timestamp":"2022-03-03 21:28:03.00 -0800","app_version":"1.2.3","slice_uuid":"5f72cbc8-f1ca-34a3-8882-bf0a879afe83","adam_id":"1436902243","build_version":"298","platform":2,"bundleID":"app.ish.iSH","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"iPhone OS 15.3.1 (19D52)","incident_id":"1A939643-E883-40F5-9DB1-DDE0B2215EC1","name":"iSH"}
{
  "uptime" : 70000,
  "procLaunch" : "2022-03-03 21:25:03.9613 -0800",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iPhone14,5",
  "procStartAbsTime" : 1686645349474,
  "coalitionID" : 443,
  "osVersion" : {
    "isEmbedded" : true,
    "train" : "iPhone OS 15.3.1",
    "releaseType" : "User",
    "build" : "19D52"
  },
  "captureTime" : "2022-03-03 21:28:03.5827 -0800",
  "incident" : "1A939643-E883-40F5-9DB1-DDE0B2215EC1",
  "bug_type" : "309",
  "pid" : 1866,
  "procExitAbsTime" : 1690956155977,
  "cpuType" : "ARM-64",
  "procName" : "iSH",
  "procPath" : "\/private\/var\/containers\/Bundle\/Application\/EC5BB5DF-9A58-47C2-B9B9-D5DA2011D316\/iSH.app\/iSH",
  "bundleInfo" : {"CFBundleShortVersionString":"1.2.3","CFBundleVersion":"298","CFBundleIdentifier":"app.ish.iSH","DTAppStoreToolsBuild":"13C90b"},
  "storeInfo" : {"storeCohortMetadata":"10|date=1643574600000&sf=143455&prpg=Genre_179183&ctxt=Search&lngid=6","itemID":"1436902243","deviceIdentifierForVendor":"8E1BF830-E52E-4255-A6C3-2D6710C273FD","softwareVersionExternalIdentifier":"846044774","thirdParty":true,"applicationVariant":"1:iPhone14,5:15"},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "app.ish.iSH",
  "crashReporterKey" : "969e42616d0b9772dfd83be243d9a5a61b412821",
  "basebandVersion" : "1.41.06",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "asi" : {"libsystem_c.dylib":["abort() called"]},
  "faultingThread" : 18,
  "threads" : [{"id":694838,"name":"login-7","queue":"com.apple.main-thread","frames":[{"imageOffset":5380,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":7068,"symbol":"mach_msg","symbolLocation":76,"imageIndex":0},{"imageOffset":30520,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":1},{"imageOffset":47660,"symbol":"__CFRunLoopRun","symbolLocation":1212,"imageIndex":1},{"imageOffset":128104,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":1},{"imageOffset":5004,"symbol":"GSEventRunModal","symbolLocation":164,"imageIndex":2},{"imageOffset":5346768,"symbol":"-[UIApplication _run]","symbolLocation":1100,"imageIndex":3},{"imageOffset":2719604,"symbol":"UIApplicationMain","symbolLocation":364,"imageIndex":3},{"imageOffset":43176,"imageIndex":4},{"imageOffset":105124,"symbol":"start","symbolLocation":520,"imageIndex":5}]},{"id":694846,"name":"com.apple.uikit.eventfetch-thread","frames":[{"imageOffset":5380,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":7068,"symbol":"mach_msg","symbolLocation":76,"imageIndex":0},{"imageOffset":30520,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":1},{"imageOffset":47660,"symbol":"__CFRunLoopRun","symbolLocation":1212,"imageIndex":1},{"imageOffset":128104,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":1},{"imageOffset":101508,"symbol":"-[NSRunLoop(NSRunLoop) runMode:beforeDate:]","symbolLocation":236,"imageIndex":6},{"imageOffset":368056,"symbol":"-[NSRunLoop(NSRunLoop) runUntilDate:]","symbolLocation":92,"imageIndex":6},{"imageOffset":4794188,"symbol":"-[UIEventFetcher threadMain]","symbolLocation":524,"imageIndex":3},{"imageOffset":427004,"symbol":"__NSThread__start__","symbolLocation":808,"imageIndex":6},{"imageOffset":6564,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3744,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":694847,"frames":[{"imageOffset":3724,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":694850,"name":"JavaScriptCore bmalloc scavenger","frames":[{"imageOffset":8080,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":33364,"symbol":"_pthread_cond_wait","symbolLocation":1228,"imageIndex":7},{"imageOffset":40412,"symbol":"std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&)","symbolLocation":28,"imageIndex":8},{"imageOffset":18747764,"symbol":"void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&)","symbolLocation":108,"imageIndex":9},{"imageOffset":18766148,"symbol":"bmalloc::Scavenger::threadRunLoop()","symbolLocation":340,"imageIndex":9},{"imageOffset":18765028,"symbol":"bmalloc::Scavenger::threadEntryPoint(bmalloc::Scavenger*)","symbolLocation":16,"imageIndex":9},{"imageOffset":18770336,"symbol":"void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(bmalloc::Scavenger*), bmalloc::Scavenger*> >(void*)","symbolLocation":48,"imageIndex":9},{"imageOffset":6564,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3744,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":694861,"name":"init-1","frames":[{"imageOffset":8080,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":33364,"symbol":"_pthread_cond_wait","symbolLocation":1228,"imageIndex":7},{"imageOffset":263696,"imageIndex":4},{"imageOffset":263412,"imageIndex":4},{"imageOffset":177856,"imageIndex":4},{"imageOffset":142384,"imageIndex":4},{"imageOffset":146088,"imageIndex":4},{"imageOffset":146320,"imageIndex":4},{"imageOffset":6564,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3744,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":694865,"name":"getty-5","frames":[{"imageOffset":8080,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":33364,"symbol":"_pthread_cond_wait","symbolLocation":1228,"imageIndex":7},{"imageOffset":263696,"imageIndex":4},{"imageOffset":263412,"imageIndex":4},{"imageOffset":244796,"imageIndex":4},{"imageOffset":188536,"imageIndex":4},{"imageOffset":142384,"imageIndex":4},{"imageOffset":146088,"imageIndex":4},{"imageOffset":146320,"imageIndex":4},{"imageOffset":6564,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3744,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":694866,"name":"getty-6","frames":[{"imageOffset":8080,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":33364,"symbol":"_pthread_cond_wait","symbolLocation":1228,"imageIndex":7},{"imageOffset":263696,"imageIndex":4},{"imageOffset":263412,"imageIndex":4},{"imageOffset":244796,"imageIndex":4},{"imageOffset":188536,"imageIndex":4},{"imageOffset":142384,"imageIndex":4},{"imageOffset":146088,"imageIndex":4},{"imageOffset":146320,"imageIndex":4},{"imageOffset":6564,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3744,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":694870,"name":"login-7","frames":[{"imageOffset":8080,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":33364,"symbol":"_pthread_cond_wait","symbolLocation":1228,"imageIndex":7},{"imageOffset":263696,"imageIndex":4},{"imageOffset":263412,"imageIndex":4},{"imageOffset":158200,"imageIndex":4},{"imageOffset":159140,"imageIndex":4},{"imageOffset":142384,"imageIndex":4},{"imageOffset":146088,"imageIndex":4},{"imageOffset":146320,"imageIndex":4},{"imageOffset":6564,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3744,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":694873,"name":"ash-8","frames":[{"imageOffset":8080,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":33364,"symbol":"_pthread_cond_wait","symbolLocation":1228,"imageIndex":7},{"imageOffset":263696,"imageIndex":4},{"imageOffset":263412,"imageIndex":4},{"imageOffset":158200,"imageIndex":4},{"imageOffset":159140,"imageIndex":4},{"imageOffset":142384,"imageIndex":4},{"imageOffset":146088,"imageIndex":4},{"imageOffset":146320,"imageIndex":4},{"imageOffset":6564,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3744,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":694888,"name":"getty-11","frames":[{"imageOffset":8080,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":33364,"symbol":"_pthread_cond_wait","symbolLocation":1228,"imageIndex":7},{"imageOffset":263696,"imageIndex":4},{"imageOffset":263412,"imageIndex":4},{"imageOffset":244796,"imageIndex":4},{"imageOffset":188536,"imageIndex":4},{"imageOffset":142384,"imageIndex":4},{"imageOffset":146088,"imageIndex":4},{"imageOffset":146320,"imageIndex":4},{"imageOffset":6564,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3744,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":694903,"name":"getty-12","frames":[{"imageOffset":8080,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":33364,"symbol":"_pthread_cond_wait","symbolLocation":1228,"imageIndex":7},{"imageOffset":263696,"imageIndex":4},{"imageOffset":263412,"imageIndex":4},{"imageOffset":244796,"imageIndex":4},{"imageOffset":188536,"imageIndex":4},{"imageOffset":142384,"imageIndex":4},{"imageOffset":146088,"imageIndex":4},{"imageOffset":146320,"imageIndex":4},{"imageOffset":6564,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3744,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":694913,"name":"getty-13","frames":[{"imageOffset":8080,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":33364,"symbol":"_pthread_cond_wait","symbolLocation":1228,"imageIndex":7},{"imageOffset":263696,"imageIndex":4},{"imageOffset":263412,"imageIndex":4},{"imageOffset":244796,"imageIndex":4},{"imageOffset":188536,"imageIndex":4},{"imageOffset":142384,"imageIndex":4},{"imageOffset":146088,"imageIndex":4},{"imageOffset":146320,"imageIndex":4},{"imageOffset":6564,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3744,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":694929,"name":"getty-14","frames":[{"imageOffset":8080,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":33364,"symbol":"_pthread_cond_wait","symbolLocation":1228,"imageIndex":7},{"imageOffset":263696,"imageIndex":4},{"imageOffset":263412,"imageIndex":4},{"imageOffset":244796,"imageIndex":4},{"imageOffset":188536,"imageIndex":4},{"imageOffset":142384,"imageIndex":4},{"imageOffset":146088,"imageIndex":4},{"imageOffset":146320,"imageIndex":4},{"imageOffset":6564,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3744,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":696326,"name":"configure-18","frames":[{"imageOffset":8080,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":33364,"symbol":"_pthread_cond_wait","symbolLocation":1228,"imageIndex":7},{"imageOffset":263696,"imageIndex":4},{"imageOffset":263412,"imageIndex":4},{"imageOffset":158200,"imageIndex":4},{"imageOffset":159140,"imageIndex":4},{"imageOffset":142384,"imageIndex":4},{"imageOffset":146088,"imageIndex":4},{"imageOffset":146320,"imageIndex":4},{"imageOffset":6564,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3744,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":696327,"name":"tee-19","frames":[{"imageOffset":9368,"symbol":"read","symbolLocation":8,"imageIndex":0},{"imageOffset":212644,"imageIndex":4},{"imageOffset":188536,"imageIndex":4},{"imageOffset":142384,"imageIndex":4},{"imageOffset":146088,"imageIndex":4},{"imageOffset":146320,"imageIndex":4},{"imageOffset":6564,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3744,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":697650,"name":"configure-1029","frames":[{"imageOffset":8080,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":33364,"symbol":"_pthread_cond_wait","symbolLocation":1228,"imageIndex":7},{"imageOffset":263696,"imageIndex":4},{"imageOffset":263412,"imageIndex":4},{"imageOffset":158200,"imageIndex":4},{"imageOffset":159140,"imageIndex":4},{"imageOffset":142384,"imageIndex":4},{"imageOffset":146088,"imageIndex":4},{"imageOffset":146320,"imageIndex":4},{"imageOffset":6564,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3744,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":697651,"name":"cc-1030","frames":[{"imageOffset":8080,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":33364,"symbol":"_pthread_cond_wait","symbolLocation":1228,"imageIndex":7},{"imageOffset":263696,"imageIndex":4},{"imageOffset":263412,"imageIndex":4},{"imageOffset":158200,"imageIndex":4},{"imageOffset":159140,"imageIndex":4},{"imageOffset":142384,"imageIndex":4},{"imageOffset":146088,"imageIndex":4},{"imageOffset":146320,"imageIndex":4},{"imageOffset":6564,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3744,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":697654,"name":"cc1-1031","frames":[{"imageOffset":286424,"imageIndex":4},{"imageOffset":286264,"imageIndex":4},{"imageOffset":288308,"imageIndex":4},{"imageOffset":287428,"imageIndex":4},{"imageOffset":146016,"imageIndex":4},{"imageOffset":146320,"imageIndex":4},{"imageOffset":6564,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3744,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"triggered":true,"id":697655,"name":"as-1032 died: sqlite error: database is locked","threadState":{"x":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":10762532625},{"value":46},{"value":0},{"value":0},{"value":4801238310864005560},{"value":4801238314859469240},{"value":12884903820},{"value":35747326421374976},{"value":85},{"value":4379123008},{"value":16383},{"value":7957840912,"symbolLocation":0,"symbol":"OBJC_CLASS_$___NSCFString"},{"value":328},{"value":6144274432},{"value":0},{"value":6},{"value":260355},{"value":6144274656},{"value":420},{"value":33346},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":8347898744},"cpsr":{"value":1073745920},"fp":{"value":6144244928},"sp":{"value":6144244896},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":7378205028,"matchesCrashFrame":1},"far":{"value":4743309107}},"frames":[{"imageOffset":31076,"symbol":"__pthread_kill","symbolLocation":8,"imageIndex":0},{"imageOffset":29560,"symbol":"pthread_kill","symbolLocation":268,"imageIndex":7},{"imageOffset":130896,"symbol":"abort","symbolLocation":164,"imageIndex":10},{"imageOffset":148928,"imageIndex":4},{"imageOffset":134912,"imageIndex":4},{"imageOffset":135556,"imageIndex":4},{"imageOffset":216532,"imageIndex":4},{"imageOffset":206272,"imageIndex":4},{"imageOffset":186100,"imageIndex":4},{"imageOffset":142384,"imageIndex":4},{"imageOffset":146088,"imageIndex":4},{"imageOffset":146320,"imageIndex":4},{"imageOffset":6564,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3744,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7378173952,
    "size" : 212992,
    "uuid" : "ff3ee512-a0bc-3123-b983-d365a71fb06a",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6447742976,
    "size" : 4538368,
    "uuid" : "e2f84645-2905-31ef-8ec7-3cc19c3cddb3",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/CoreFoundation",
    "name" : "CoreFoundation"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6913056768,
    "size" : 36864,
    "uuid" : "b40e3b17-90c7-3ebc-b6bc-8c7b605f47a9",
    "path" : "\/System\/Library\/PrivateFrameworks\/GraphicsServices.framework\/GraphicsServices",
    "name" : "GraphicsServices"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6486183936,
    "size" : 25739264,
    "uuid" : "920a0ee6-d266-3058-8144-27a27b23ad62",
    "path" : "\/System\/Library\/PrivateFrameworks\/UIKitCore.framework\/UIKitCore",
    "name" : "UIKitCore"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4330045440,
    "size" : 671744,
    "uuid" : "5f72cbc8-f1ca-34a3-8882-bf0a879afe83",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/EC5BB5DF-9A58-47C2-B9B9-D5DA2011D316\/iSH.app\/iSH",
    "name" : "iSH"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4333846528,
    "size" : 360448,
    "uuid" : "780553c7-d39f-322a-8cb9-f4f6de52610d",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6473060352,
    "size" : 3174400,
    "uuid" : "925a43cd-eaf2-3161-9378-3ed87468301d",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Foundation",
    "name" : "Foundation"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8347869184,
    "size" : 49152,
    "uuid" : "a17d07cf-e86a-3923-87c4-921045898a8a",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6860333056,
    "size" : 409600,
    "uuid" : "346a1fc1-f0b3-37db-b102-09951bb9aa78",
    "path" : "\/usr\/lib\/libc++.1.dylib",
    "name" : "libc++.1.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6632407040,
    "size" : 19861504,
    "uuid" : "8882e299-ecd2-36a1-839b-41ee2ca83aa6",
    "path" : "\/System\/Library\/Frameworks\/JavaScriptCore.framework\/JavaScriptCore",
    "name" : "JavaScriptCore"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6631526400,
    "size" : 520192,
    "uuid" : "9b299ee5-b379-3856-848b-524d82640dbc",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  }
],
  "sharedCache" : {
  "base" : 6444302336,
  "size" : 2515517440,
  "uuid" : "a2d995b8-2459-39e3-9035-04cf974f8d50"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=651.5M resident=0K(0%) swapped_out_or_unallocated=651.5M(100%)\nWritable regions: Total=682.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=682.3M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nCG raster data                    1456K       16 \nColorSync                           32K        2 \nCoreAnimation                      224K       12 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           652.4M     1848 \nMALLOC guard page                  192K       12 \nSQLite page cache                  640K       10 \nSTACK GUARD                        304K       19 \nStack                             10.5M       19 \nVM_ALLOCATE                       7248K      169 \nVM_ALLOCATE (reserved)             448K       28         reserved VM address space (unallocated)\nWebKit Malloc                     8400K       15 \n__AUTH                            3262K      350 \n__AUTH_CONST                      17.8M      479 \n__DATA                            14.5M      467 \n__DATA_CONST                      18.3M      484 \n__DATA_DIRTY                      1502K      402 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       188.1M        5 \n__OBJC_CONST                      4306K      326 \n__OBJC_RO                         91.2M        1 \n__OBJC_RW                         3488K        1 \n__TEXT                           463.4M      495 \n__UNICODE                          588K        1 \ndyld private memory               1024K        1 \nlibnetwork                         128K        8 \nmapped file                      231.6M      177 \nshared memory                       48K        3 \n===========                     =======  ======= \nTOTAL                              1.7G     5354 \nTOTAL, minus reserved VM space     1.7G     5354 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "name" : "as-1032 died: sqlite error: database is locked"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "61fb0e59c773c43cde3bb80d"
      },
      "deploymentId" : 240000305
    },
    {
      "rolloutId" : "60509d56f2766876dee21c11",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_ASR_ASSISTANT" : "61fb11b9c773c43cde3bb81d",
        "SIRI_UNDERSTANDING_NL" : "61de1d0db1ed363a74899508",
        "SIRI_UNDERSTANDING_MORPHUN" : "610072c2f6774779a7ced014",
        "SIRI_EXPERIENCE_CAM" : "619444cf2171a2330e561f60"
      },
      "deploymentId" : 240000605
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_ASR_HAMMER" : "621522708f87212159690464"
      },
      "deploymentId" : 240000249
    },
    {
      "rolloutId" : "602c34a3046661000c9ebdde",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_NL_OVERRIDES" : "62151dde53dd55727da80161"
      },
      "deploymentId" : 240000616
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000115
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "621d4d11f441df278b2334c9"
      },
      "deploymentId" : 240000406
    }
  ],
  "experiments" : [

  ]
}
}
```

stdout of configure until crash:

```
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether cc accepts -g... yes
checking for cc option to enable C11 features... none needed
checking if cc supports C99-style variadic macros... yes
checking build system type... i686-pc-linux-musl
checking host system type... i686-pc-linux-musl
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking how to run the C preprocessor... cc -E
checking for ranlib... ranlib
checking for a BSD-compatible install... /usr/bin/install -c
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a race-free mkdir -p... ./install-sh -c -d
checking for ar... ar
checking for cat... /bin/cat
checking for kill... /bin/kill
checking for sed... /bin/sed
checking for bash... /bin/bash
checking for ksh... (cached) /bin/bash
checking for sh... (cached) /bin/bash
checking for sh... /bin/sh
checking for groff... no
checking for nroff... no
checking for mandoc... /usr/bin/mandoc
checking for groupadd... groupadd
checking for useradd... useradd
checking for pkgmk... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for passwd... /usr/bin/passwd
checking for inline... inline
checking for cc options needed to detect all undeclared functions... none needed
checking whether LLONG_MAX is declared... yes
checking whether LONG_LONG_MAX is declared... no
checking whether SYSTR_POLICY_KILL is declared... no
checking whether RLIMIT_NPROC is declared... yes
checking whether PR_SET_NO_NEW_PRIVS is declared... no
checking whether OpenSSL will be used for cryptography... yes
checking if cc supports -Werror... yes
checking if cc supports compile flag -pipe... yes
checking if cc supports compile flag -Wunknown-warning-option... no
checking if cc supports compile flag -Wno-error=format-truncation... yes
checking if cc supports compile flag -Qunused-arguments... no
checking if cc supports compile flag -Wall... yes
checking if cc supports compile flag -Wextra... no
checking if cc supports compile flag -Wpointer-arith... yes
checking if cc supports compile flag -Wuninitialized... yes
checking if cc supports compile flag -Wsign-compare... yes
checking if cc supports compile flag -Wformat-security... yes
checking if cc supports compile flag -Wsizeof-pointer-memaccess... yes
checking if cc supports compile flag -Wpointer-sign... yes
checking if cc supports compile flag -Wunused-parameter... no
checking if cc supports compile flag -Wunused-result... yes
checking if cc supports compile flag -Wimplicit-fallthrough... yes
checking if cc supports compile flag -Wmisleading-indentation... yes
checking if cc supports compile flag -Wbitwise-instead-of-logical... no
checking if cc supports compile flag -fno-strict-aliasing... yes
checking if cc supports compile flag -mretpoline... no
checking if cc supports link flag -Wl,-z,retpolineplt... no
checking if cc supports compile flag -D_FORTIFY_SOURCE=2... yes
checking if cc supports link flag -Wl,-z,relro... yes
checking if cc supports link flag -Wl,-z,now... yes
checking if cc supports link flag -Wl,-z,noexecstack... yes
checking if cc supports compile flag -ftrapv and linking succeeds... yes
checking if cc supports compile flag -fzero-call-used-regs=all... no
checking if cc supports compile flag -ftrivial-auto-var-init=zero... no
checking gcc version... 10.3.1
checking if cc accepts -fno-builtin-memset... yes
checking if cc supports -fstack-protector-strong... yes
checking if -fstack-protector-strong works... yes
checking if compiler allows __attribute__ on return types... yes
checking if compiler allows __attribute__ prototype args... yes
checking if compiler supports variable length arrays... yes
checking if compiler accepts variable declarations after code... yes
checking for blf.h... no
checking for bstring.h... no
checking for crypt.h... yes
checking for crypto/sha2.h... no
checking for dirent.h... yes
checking for endian.h... yes
checking for elf.h... yes
checking for err.h... yes
checking for features.h... yes
checking for fcntl.h... yes
checking for floatingpoint.h... no
checking for fnmatch.h... yes
checking for getopt.h... yes
checking for glob.h... yes
checking for ia.h... no
checking for iaf.h... no
checking for ifaddrs.h... yes
checking for inttypes.h... (cached) yes
checking for langinfo.h... yes
checking for limits.h... yes
checking for locale.h... yes
checking for login.h... no
checking for maillock.h... no
checking for ndir.h... no
checking for net/if_tun.h... 
```

**Comment by kouwei32** [comment] 2022-03-04 05:46
Seems like the bug is inconsistent and crashes at a different place each time. This time it crashes at the check for `bzero`

**Comment by saagarjha** [comment] 2022-03-05 10:14
This seems like a duplicate of #1734, so I'm going to close it and redirect discussion there.

**Closed by saagarjha** 2022-03-05 10:14 UTC
Labels: unconfirmed
