### ISSUE TITLE
Wifi Not Detecting!

### ISSUE THREAD

**Issue by AnikinKocur** [ish-app/ish#1753] opened 2022-03-16 03:40 UTC
Hello guys! I have a little problem here. When i write "airmon-ng" it doesn’t show any wifi available:   

iPhone:~# airmon-ng

ls: /sys/class/net: No such file or directory
PHY     Interface       Driver          Chipset

——————————————————————-
When i write "ip addr" it doesn’t work too :

iPhone:~# ip addr
ip: socket(AF_NETLINK,3,0): Invalid argument

So is there a way to fix this or I have to wait for the dev to fix this?

**Comment by Mnpn** [comment] 2022-03-18 16:03
Hi! I'm closing this as a duplicate of #145 (and #639). This networking API isn't implemented in iSH, though if you would like to fix it yourself we always welcome [pull requests](https://github.com/ish-app/ish/pulls) :)

**Closed by Mnpn** 2022-03-18 16:03 UTC
Labels: unconfirmed

**Comment by adamnn2006** [comment] 2024-07-09 00:58
@Mnpn is the problem fixed yet cuz my iphone still can't get gawk
