### ISSUE TITLE
IPad Pro with iPad Pro keyboard, when the ish app loses focus it is difficult to return focus to ish app

### ISSUE THREAD

**Issue by khappucino** [ish-app/ish#969] opened 2020-10-25 00:56 UTC
On IPad Pro 12.9 when I move the focus to another app and then try to return focus to ish, the cursor is not activated and keyboard inputs are ignored. One workaround that I have found is pressing down on the trackpad on the ish application window while simultaneously clicking keys, eventually the key inputs will show up in the terminal and then I can let go of the trackpad.

**Comment by swiftmas** [comment] 2020-10-29 16:06
I have noticed this same behavior with 2 separate Bluetooth keyboards. The issue i had was in split-view between textastic and iSH as well as safari. in order to switch between I had to summon the phone sized pop-out window from the right hand side then immediately tap on one of the two programs to switch between them. Ironically in my case iSH never had an issue picking up the focus while textastic regularly had issues.

**Comment by jotkali** [comment] 2020-11-08 04:34
I am also having this issue with a magic keyboard and an iPad 11"

**Comment by mpjalexander** [comment] 2020-11-22 19:44
I've also had this issue using an iPad Pro 11" and Magic Keyboard. It only happens for me if I try and use split view (either with another app, or a second instance of iSH). Happy to test and provide feedback on any fixes.

**Comment by HappyStriker** [comment] 2020-11-29 10:04
I have experienced this issue as well. At least there is a simpler workaround than described above: Tap multiple times somewhere on the terminal window and then after a few times the focus will be restored.
Still, a proper fix is very much appreciated. Thank you very much!

**Comment by felipereisdev** [comment] 2021-01-09 21:04
I also have the same problem

**Comment by tbodt** [comment] 2021-06-01 09:11
I think this is a duplicate of #731

**Closed by tbodt** 2021-06-01 09:11 UTC
Labels: fuck webview

**Comment by SugarRayLua** [comment] 2021-07-04 23:08
Dear iSH Community,

I’ve experience a slightly different version of the same question: namely, that the app I’m working with in split view looses keyboard focus easily, especially if I try and try and go back to using the iSH app for a while. It especially happens when I use split to host iSH as a VNC or SSH sever and then use another client app in split view as a client.

I searched the web for a while and learned that others have had the same problem with other apps besides iSH. What has consistently worked for them and me now is to use the keyboard shortcut to the ‘app switcher’ by holding down CMD + TAB. That will bring up a selection of recently opened apps, and (without letting up on the CMD button) I use the arrow keys to select the app I’m wanting to get keyboard focus back in split view. Seems to work every time and not too much of a hassle. The only thing I’ve had to remember is to make sure the app I’m using in side view has been recently opened; otherwise, it sometimes doesn’t appear in the app selector for some reason to choose. I suspect others could use this same strategy to select iSH back into focus.

Fyi.
