### ISSUE TITLE
How do I get Wi-Fi on ish

### ISSUE THREAD

**Issue by michael809-byte** [ish-app/ish#1252] opened 2021-01-21 21:45 UTC
I’m trying to run a specific tool but the tool keeps telling me that I need a internet connection but I’m connected to wifi on my iPad so is there a way for me to get wifi on ish?

**Comment by tbodt** [comment] 2021-01-21 22:19
Internet works in iSH automatically. What method of internet detection isn't working?

**Comment by michael809-byte** [comment] 2021-01-21 22:22
A github repository someone made i really liked so i tried using it put it
says i need a network connection plus I’m connected to wifi on my ipad but
in ish shell my wifi doesn’t work plus its using same dns as my network and
still nothing so is there a way for ish to get a network connection?

**Comment by michael809-byte** [comment] 2021-01-21 22:24
Look 
![1020C924-90E0-4CA1-9985-FDBFFB50A600](https://user-images.githubusercontent.com/77212666/105419959-2b8a2e00-5c05-11eb-96b3-4e0b4229fb7f.png)

**Comment by tbodt** [comment] 2021-01-21 22:26
Duplicate of #145

**Closed by tbodt** 2021-01-21 22:26 UTC
Labels: unconfirmed
