### ISSUE TITLE
Non-ascii characters cannot be shown in ish terminal after IOS updated to 14.5.1

### ISSUE THREAD

**Issue by biao-biao** [ish-app/ish#1405] opened 2021-05-10 03:22 UTC

**Comment by ferrmin** [comment] 2021-05-10 09:22
+1

**Comment by SugarRayLua** [comment] 2021-05-10 16:15
Similar concern to my UTF-8 comment in #1395?

**Comment by schabrolles** [comment] 2021-05-24 08:36
may be related to this issue, but tmux split pane doesn't work anymore

**Comment by tbodt** [comment] 2021-06-01 00:43
I believe this is a duplicate of #1423, which is now fixed

**Closed by tbodt** 2021-06-01 00:43 UTC
