### ISSUE TITLE
Emacs 26.2 “Failed select: Invalid argument”

### ISSUE THREAD

**Issue by DeepakTivari** [ish-app/ish#727] opened 2020-05-19 13:44 UTC
Fresh install of emacs gives this error:
Failed select: Invalid argument

![D45EB311-651B-47FA-8ED6-C6B13EEB9E39](https://user-images.githubusercontent.com/8651699/82333899-e0869e00-9a19-11ea-91be-1ca6efb3183c.png)

**Comment by tbodt** [comment] 2020-05-19 20:51
Duplicate of #711

**Closed by tbodt** 2020-05-19 20:51 UTC
