### ISSUE TITLE
paddd

### ISSUE THREAD

**Issue by 62f** [ish-app/ish#923] opened 2020-09-29 22:30 UTC
https://github.com/rust-lang/rust/pull/71586#issuecomment-626328134 indicates that [    0.000000] 17 illegal instruction at 0x56cd15be: 0f fe e1 66 0f df dc 66 is not an iSH bug, despite the existence of both Rust/“rustup” and Cargo .apk packages in Alpine 3.12 since the latter depends on the former, neither will currently run.

_Originally posted by @62f in https://github.com/ish-app/ish/issues/67#issuecomment-675897501_

 [    0.000000] 880 stub syscall 375
               2110 stub syscall 375
 #           2110 illegal instruction at 0x565b6c44: 0f fe d9 0f 57 c3 0f 28

**Comment by saagarjha** [comment] 2020-09-29 23:08
This is `paddd`, not a Rust bug. iSH doesn’t support it yet.

**Comment by 62f** [comment] 2020-10-23 22:04
Is this also paddd?

~ # curl -sSL https://get.haskellstack.org/ | sh
Illegal instruction
[    0.000000] 291 stub syscall 375
               291 illegal instruction at 0x565b6c44: 0f fe d9 0f 57 c3 0f 28

**Comment by saagarjha** [comment] 2020-10-23 22:05
It is indeed.

**Comment by tbodt** [comment] 2020-11-30 02:18
Looks like a duplicate of #805

**Closed by tbodt** 2020-11-30 02:18 UTC
