### ISSUE TITLE
Bad api calls in nmap

### ISSUE THREAD

**Issue by gitdev-bash** [ish-app/ish#1754] opened 2022-03-18 15:53 UTC
ISH: v1.2.4-Build-342-Alpine v3.14

nmap fails to create sockets in Alpine v3.14, yet in an older version of alpine (very old ish alpine) it works

`route_dst_netlink: cannot create AF_NETLINK socket: Invalid argument`

**Comment by Mnpn** [comment] 2022-03-18 15:56
Closing as a duplicate of #166, please post relevant information there!

**Closed by Mnpn** 2022-03-18 15:56 UTC
Labels: unconfirmed
