### ISSUE TITLE
Node: Illegal Instruction

### ISSUE THREAD

**Issue by onatbas** [ish-app/ish#1675] opened 2021-12-31 04:12 UTC
switched to a new phone, running iPhone 15.1, ish version 1.2.3 - Build 298. 

I installed NPM and Node and I’m getting illegal instruction messages. These commands used to work before.

```
Onats-iPhone:~/secretcv# node
Illegal instruction
Onats-iPhone:~/secretcv# dmesg
6 stub syscall 383
6 stub syscall 383
9 stub syscall 383
9 stub syscall 383
9 stub syscall 383
9 stub syscall 383
10 stub syscall 383
10 stub syscall 383
10 stub syscall 383
10 stub syscall 383
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383
15 stub syscall 383
15 stub syscall 383
15 stub syscall 383
15 stub syscall 383
15 stub syscall 383
15 stub syscall 383
15 stub syscall 383
15 stub syscall 383
15 stub syscall 383
15 stub syscall 383
15 stub syscall 383
15 stub syscall 383
15 stub syscall 383
15 stub syscall 375
15 illegal instruction at 0x56fbd21d: 66 0f c2 d1 02 66 0f 54 
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383
23 stub syscall 383
23 stub syscall 383
23 stub syscall 383
23 stub syscall 383
23 stub syscall 383
23 stub syscall 383
23 stub syscall 383
23 stub syscall 383
23 stub syscall 383
23 stub syscall 383
23 stub syscall 383
23 stub syscall 383
23 stub syscall 383
23 stub syscall 375
23 illegal instruction at 0x56fbd21d: 66 0f c2 d1 02 66 0f 54 
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383
31 stub syscall 383
31 stub syscall 383
31 stub syscall 383
31 stub syscall 383
31 stub syscall 383
31 stub syscall 383
31 stub syscall 383
31 stub syscall 383
31 stub syscall 383
31 stub syscall 383
31 stub syscall 383
31 stub syscall 383
31 stub syscall 383
31 stub syscall 375
31 illegal instruction at 0x56fbd21d: 66 0f c2 d1 02 66 0f 54 
39 stub syscall 383
39 stub syscall 383
39 stub syscall 383
39 stub syscall 383
39 stub syscall 383
39 stub syscall 383
39 stub syscall 383
39 stub syscall 383
39 stub syscall 383
39 stub syscall 383
39 stub syscall 383
39 stub syscall 383
39 stub syscall 383
39 stub syscall 375
39 illegal instruction at 0x56fbd21d: 66 0f c2 d1 02 66 0f 54 
```

**Comment by saagarjha** [comment] 2021-12-31 10:44
This is a duplicate of #1482.

**Closed by saagarjha** 2021-12-31 10:44 UTC
Labels: unconfirmed
