### ISSUE TITLE
I/O ERROR during apk install 

### ISSUE THREAD

**Issue by F3000** [ish-app/ish#1213] opened 2021-01-01 19:00 UTC
We're trying to collect diagnostics for an Apple bug report. If this happens to you, please immediately [capture a sysdiagnose](https://www.jessesquires.com/blog/2018/02/08/how-to-sysdiagnose-ios/) (press both volume buttons and the power button simultaneously for a few seconds) and send this to me, along with the approximate date and time the issue occurred and the output of `dmesg`. Thanks! ~@tbodt

---

i get following error . Any idea ?

![D6AF50D0-52A5-4951-8B21-FFEEB629DC68](https://user-images.githubusercontent.com/8161283/103444757-faed4f00-4c6b-11eb-85e5-65329c88b34e.png)

**Comment by kode54** [comment] 2021-01-02 07:24
I can't confirm that error, as I already have apk installed on both my devices, but I get an I/O error attempting to run `apk add iperf3`.

**Comment by andreasmerkel** [comment] 2021-01-07 14:59
Hi,
I had the same error. After deleting and reinstalling the app, I'm not able to upgrade or install any package.  (For example:
`X:~# apk add rsync` 
`(1/4) Upgrading ssl_client (1.31.1-r16 -> 1.31.1-r19)`
`ERROR: ssl_client-1.31.1-r19: IO ERROR`
and so on

**Comment by yakuzadave** [comment] 2021-01-12 04:57
It looks like I am running into this as well.

**Comment by mike-seagull** [comment] 2021-01-19 22:28
@andreasmerkel had this same issue after reinstall. Fixed it by adding apk repos https://github.com/ish-app/ish/wiki/Using-Alpine-Linux-repositories

**Comment by quartzjer** [comment] 2021-01-20 04:28
I’m also stuck, this is after deleting and a fresh re-install:

```
Welcome to Alpine!

You can install packages with: apk add <package>

You may change this message by editing /etc/motd.

pp:~# wget -qO- http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86/apk-tools-static-2.10.5-r1.apk | tar -xz sbin/apk.static && ./sbin/apk.static add apk-tools 
&& rm sbin/apk.static
(1/2) Installing ca-certificates (20191127-r4)
ERROR: ca-certificates-20191127-r4: IO ERROR
(2/2) Installing nghttp2-libs (1.41.0-r0)
ERROR: nghttp2-libs-1.41.0-r0: IO ERROR
2 errors; 6 MiB in 16 packages
pp:~# mkdir -p /ish/apk && printf 'file:///ish/apk/main\nfile:///ish/apk/community\n' > /etc/apk/repositories && mount -t apk apk /ish/apk && tar -xf /ish/apk/m
ain/x86/apk-tools-static-2.10.5-r1.apk -C / && apk.static add apk-tools && rm /sbin/apk.static && apk upgrade
mkdir: can't create directory '/ish/apk': Operation not permitted
pp:~# printf 'file:///ish/apk/main\nfile:///ish/apk/community\n' > /etc/apk/repositories && tar -xf /ish/apk/main/x86/apk-tools-static-2.10.5-r1.apk -C / && apk
.static add apk-tools && rm /sbin/apk.static && apk upgrade
tar: can't open '/ish/apk/main/x86/apk-tools-static-2.10.5-r1.apk': I/O error
pp:~# grep -v "file:///ish/apk/" /etc/apk/repositories | dd of=/etc/apk/repositories bs=4194304
0+0 records in
0+0 records out
pp:~# echo https://dl-cdn.alpinelinux.org/alpine/v3.12/main >> /etc/apk/repositories
pp:~# echo https://dl-cdn.alpinelinux.org/alpine/v3.12/community >> /etc/apk/repositories
pp:~# printf 'file:///ish/apk/main\nfile:///ish/apk/community\n' > /etc/apk/repositories && tar -xf /ish/apk/main/x86/apk-tools-static-2.10.5-r1.apk -C / && apk
.static add apk-tools && rm /sbin/apk.static && apk upgrade
tar: can't open '/ish/apk/main/x86/apk-tools-static-2.10.5-r1.apk': I/O error
pp:~# 
```

**Comment by andreasmerkel** [comment] 2021-01-20 08:26
@mike-seagull: Thanks for your hint. That solved my problem!

**Comment by 62f** [comment] 2021-01-20 15:33
I/O*

**Comment by joltcan** [comment] 2021-01-20 18:33
Tried with the workarounds, but whatever I do I get the I/O error on 1.1.1.

I can mount the apk dir but never write to it.

**Comment by RowanKaag** [comment] 2021-02-07 12:03
I was able to fix this by running:

echo "http://dl-cdn.alpinelinux.org/alpine/latest-stable/main/" > /etc/apk/repositories

echo "http://dl-cdn.alpinelinux.org/alpine/latest-stable/community/" >> /etc/apk/repositories 

apk update
apk upgrade

**Comment by quartzjer** [comment] 2021-02-07 17:49
Just an FYI, today I did another delete and fresh re-install and now everything is happy again.

**Comment by m-rossi** [comment] 2021-02-07 18:24
> Just an FYI, today I did another delete and fresh re-install and now everything is happy again.

I can confirm that

**Comment by channprj** [comment] 2021-02-11 14:51
@RowanKaag Thank you for saving my life! :+1:

**Comment by tommycusick** [comment] 2021-04-19 04:06
Hi all, just reproduced this issue.  I’m capturing a sysdiagnose (to where should I send it?), but in the meantime, here’s my terminal output on a 2018 iPad Pro:

```
Tommys-iPad:~# apk upgrade
(1/2) Upgrading alpine-baselayout (3.2.0-r6 -> 3.2.0-r7)
ERROR: alpine-baselayout-3.2.0-r7: IO ERROR
(2
<img width="1366" alt="IO ERROR dmesg" src="https://user-images.githubusercontent.com/221021/115180187-db96f800-a089-11eb-8734-b9c64f1292b8.png">
/2) Upgrading ssl_client (1.31.1-r16 -> 1.31.1-r20)
ERROR: ssl_client-1.31.1-r20: IO ERROR
2 errors; 5 MiB in 14 packages
Tommys-iPad:~# dmesg
error fetching ODR main:x86:alpine-baselayout-3.2.0-r7.apk: Error Domain=AssetErrorDomain Code=6 "Asset URL has expired" UserInfo={NSDebugDescription=Asset URL has expired}
error fetching ODR main:x86:ssl_client-1.31.1-r20.apk: Error Domain=AssetErrorDomain Code=6 "Asset URL has expired" UserInfo={NSDebugDescription=Asset URL has expired}
Tommys-iPad:~# 
```

**Comment by logolept** [comment] 2021-04-20 00:38
I captured the sysdiagnose at 2021-04-19 19:02-05:00.
```
Welcome to Alpine!

You can install packages with: apk add <package>

You may change this message by editing /etc/motd.

iPhone:~# apk update&&apk upgrade
WARNING: Ignoring file:///ish/apk/main/x86/APKINDEX.tar.gz: Interrupted system call
WARNING: Ignoring file:///ish/apk/community/x86/APKINDEX.tar.gz: Interrupted system call
OK: 14 distinct packages available
WARNING: Ignoring file:///ish/apk/main/x86/APKINDEX.tar.gz: Interrupted system call
WARNING: Ignoring file:///ish/apk/community/x86/APKINDEX.tar.gz: Interrupted system call
OK: 5 MiB in 14 packages
iPhone:~# apk update&&apk upgrade
WARNING: Ignoring file:///ish/apk/main/x86/APKINDEX.tar.gz: Interrupted system call
WARNING: Ignoring file:///ish/apk/community/x86/APKINDEX.tar.gz: Interrupted system call
OK: 14 distinct packages available
WARNING: Ignoring file:///ish/apk/main/x86/APKINDEX.tar.gz: Interrupted system call
WARNING: Ignoring file:///ish/apk/community/x86/APKINDEX.tar.gz: Interrupted system call
OK: 5 MiB in 14 packages
iPhone:~# apk update&&apk upgrade
v3.12.7-2-gffff8a3871 [file:///ish/apk/main]
v3.12.6-26-gd971503b0a [file:///ish/apk/community]
OK: 12543 distinct packages available
Upgrading critical system libraries and apk-tools:
(1/1) Upgrading apk-tools (2.10.5-r1 -> 2.10.6-r0)
ERROR: apk-tools-2.10.6-r0: IO ERROR
Continuing the upgrade transaction with new apk-tools:
(1/3) Upgrading busybox (1.31.1-r19 -> 1.31.1-r20)
Executing busybox-1.31.1-r20.post-upgrade
(2/3) Upgrading ssl_client (1.31.1-r19 -> 1.31.1-r20)
ERROR: ssl_client-1.31.1-r20: IO ERROR
(3/3) Upgrading apk-tools (2.10.5-r1 -> 2.10.6-r0)
ERROR: apk-tools-2.10.6-r0: IO ERROR
Executing busybox-1.31.1-r20.trigger
2 errors; 5 MiB in 14 packages
iPhone:~# dmesg
error fetching ODR main:x86:apk-tools-2.10.6-r0.apk: Error Domain=AssetErrorDomain Code=6 "Asset URL has expired" UserInfo={NSDebugDescription=Asset URL has expired}
error fetching ODR main:x86:ssl_client-1.31.1-r20.apk: Error Domain=AssetErrorDomain Code=6 "Asset URL has expired" UserInfo={NSDebugDescription=Asset URL has expired}
error fetching ODR main:x86:apk-tools-2.10.6-r0.apk: Error Domain=AssetErrorDomain Code=6 "Asset URL has expired" UserInfo={NSDebugDescription=Asset URL has expired}
iPhone:~# 
```
sysdiagnose:

> https://drive.google.com/file/d/1FVvVoonrv9zOaOYBDMBW_DaUfJEEq7ue/view

**Comment by Tux-the-Penguin** [comment] 2021-04-23 21:23
Try adding the default Alpine Linux repositories:
`# echo "http://dl-cdn.alpinelinux.org/alpine/latest-stable/main/" > /etc/apk/repositories`
`# echo "http://dl-cdn.alpinelinux.org/alpine/latest-stable/community/" >> /etc/apk/repositories`

**Comment by Mnpn03** [comment] 2021-04-27 09:21
These errors should be resolved in iSH 1.2. If you are still experiencing this on 1.2, please let us know and we'll reopen this issue.

**Closed by Mnpn03** 2021-04-27 09:21 UTC

**Comment by RowanKaag** [comment] 2021-04-28 08:58
Any pointers on the cause @Mnpn03 ? I noticed that APK is now looking at apk.ish.app. Is the "On-Demand Resources"-feature only supposed to work with the root domain of the apps' registered domain?

**Comment by 62f** [comment] 2021-05-06 00:25
![image](https://user-images.githubusercontent.com/68332197/117225294-fedada80-addf-11eb-8128-914aceb26b79.jpeg)

**Comment by kode54** [comment] 2021-05-06 00:30
Cool, a unique error that hasn't been reported anywhere on the Internet before.

**Comment by 62f** [comment] 2021-05-07 10:15
A more concise verb for decoding a raster image into some language's equivalent typeset characters would be 'transliterating'.
Does googlebot lurk in here on the dark web?

**Comment by Gopz1431** [comment] 2022-04-18 21:38
Not running still stuck

**Comment by Gopz1431** [comment] 2022-04-18 21:39
![image](https://user-images.githubusercontent.com/103906849/163882041-accfe5d9-4353-467a-96bf-8b5e60a79723.png)



Still not running stuck in 25 percentage

**Comment by leocabbage2008** [comment] 2024-09-18 02:32
> I was able to fix this by running:
> 
> echo "http://dl-cdn.alpinelinux.org/alpine/latest-stable/main/" > /etc/apk/repositories
> 
> echo "http://dl-cdn.alpinelinux.org/alpine/latest-stable/community/" >> /etc/apk/repositories
> 
> apk update apk upgrade

top dawg you my diddle
