### ISSUE TITLE
rust / rustup

### ISSUE THREAD

**Issue by rhysforyou** [ish-app/ish#67] opened 2018-11-13 01:29 UTC
Not unsurprisingly, Rust doesn't seem to install currently:

```sh
Rhyss-iPhone:~# curl https://sh.rustup.rs -sSf | sh
curl: (56) LibreSSL SSL_read: error:06FFF064:digital envelope routines:CRYPTO_internal:bad decrypt, errno 0
rustup: command failed: downloader https://static.rust-lang.org/rustup/dist/i686-unknown-linux-gnu/rustup-init /tmp/tmp.aMfBBO/rustup-init
```

Mostly reporting here so we can add it to the compatibility table.

**Comment by rhysforyou** [comment] 2018-11-26 00:32
As of the latest build, here’s what I get when running that command:

```
Rhyss-iPhone:~# curl https://sh.rustup.rs -sSf |                                       sh                                                                                               
info: downloading installer                                                                      
sh: can't open /dev/tty: no such file
```

**Comment by tbodt** [comment] 2018-11-26 00:32
That error is the same as the one preventing ssh from reading passwords from stdin.

**Comment by jasonehines** [comment] 2018-11-29 21:42
I installed bash and ran the script with -y to get around the tty issue, but it then just crashed the entire app

**Comment by tbodt** [comment] 2018-12-07 23:56
/dev/tty and segfault issues are fixed, but now it turns out rustup doesn't work on alpine. You'll have to install rust through apk.

**Comment by tbodt** [comment] 2018-12-07 23:58
And you can't install rust through apk because they only have 64-bit binaries...

**Comment by amanjeev** [comment] 2018-12-09 19:41
@tbodt so rust works or doesn't work? I cannot install it via apk or rustup script.

**Comment by tbodt** [comment] 2018-12-09 19:50
It doesn’t work and I’m not sure how to make it work. Maybe I should make a new column for that sort of thing ?

**Comment by amanjeev** [comment] 2018-12-09 20:04
I would vote for a new column with a label like help needed? It might encourage contribution as well as a side effect. What do you think?

**Comment by tbodt** [comment] 2018-12-09 20:17
I moved it back to Doesn’t Work. Possibilities for getting it to work:

- Install 32-bit glibc. This requires building it from source.
- Build rustc from source for 32-bit musl. This is not supported by the rust project.
- Switch to a Linux distribution that uses glibc, like Ubuntu. This would make the app download 10 times bigger, and require a reinstall to get it if I don’t implement multiple root filesystems first.
- Make iSH support 64-bit. This would take probably at least 6 months.

**Comment by amanjeev** [comment] 2018-12-09 20:33
@tbodt  Thank you for the response. I have little experience with system programming like this so I really cannot comment on any of those solutions except that Rust support isn't that urgent so if you have a plan for 64-bit support, I would vote for that instead of anything else.

And if you can plan out and want to farm out some tasks for newbies like me, this could be fun as well. Maybe? :grinning:

**Comment by tbodt** [comment] 2018-12-09 20:56
I would love to have more people contributing, but this is not an easy project to contribute to. You’d need to be pretty good at C and Linux to work on it.

**Comment by tbodt** [comment] 2018-12-10 21:32
They don’t seem to have a 32-bit version available for download.

**Comment by jasonehines** [comment] 2018-12-10 22:21
They have 32-bit on this page: https://help.ubuntu.com/l/Installation/MinimalCD

**Comment by tbodt** [comment] 2018-12-10 22:21
That link gives a 404.

**Comment by tbodt** [comment] 2018-12-10 22:33
I found a 32-bit rootfs for Ubuntu Base here: http://cdimage.ubuntu.com/ubuntu-base/releases/18.04/release/

**Comment by HomeLH** [comment] 2019-04-25 12:18
I met the same problom when I installed rust on ubuntu 18.04.
But, the following command line works well without arguments -sSf.
`curl https://sh.rustup.rs | sh`

**Comment by kkk669** [comment] 2019-05-22 16:18
@corbinu

> I think once this is merged then a 32bit build for musl shouldn't be to hard: rust-lang/rust#55163

Rust 1.35.0, which is released on May 24, [supports for x86_64-unknown-linux-musl](https://github.com/rust-lang/rust/pull/58575). 🎉

But, i686-unknown-linux-musl is still not supported by rustc and cargo.
https://forge.rust-lang.org/platform-support.html

**Comment by tbodt** [comment] 2020-02-06 19:48
Update on rust: it's in the Alpine edge repo. rustup is not going to work very well.

**Comment by corbinu** [comment] 2020-02-06 20:33
@tbodt I have been using rustup in Alpine for a bit now. It seems to be working fine haven't seen any issues.

**Comment by kkk669** [comment] 2020-02-07 13:44
@tbodt I upgraded my Alpine Linux on iSH 1.0 build 64 from v3.10 to edge by following [the article](https://wiki.alpinelinux.org/wiki/Edge), then installed `cargo` package. Installation itself was succeeded, but both `rustc` and `cargo` is killed by SIGILL immediately.

Do you have any suggestions?

![IMG_0193](https://user-images.githubusercontent.com/601636/74033967-a78e6480-49fa-11ea-9bda-799949c5d91c.png)

**Comment by tbodt** [comment] 2020-02-10 02:35
@kkk669 What does `dmesg` say? My hunch is it's SSE2.

**Comment by kkk669** [comment] 2020-02-10 02:42
@tbodt Is this enough?

```console
# cargo
fish: 'cargo' terminated by signal SIGILL (Illegal instruction)
root@Satanas-beetle ~# dmesg
8 stub syscall 375
43 illegal instruction at 0x56d3b9fd: f2 0f 10 45 e8 89 48 08 
# rustc
fish: 'rustc' terminated by signal SIGILL (Illegal instruction)
# dmesg
8 stub syscall 375
43 illegal instruction at 0x56d3b9fd: f2 0f 10 45 e8 89 48 08 
61 illegal instruction at 0xf4d96a0d: f2 0f 10 45 e8 89 48 08
```

**Comment by tbodt** [comment] 2020-02-10 02:43
Yep that's movsd, which is SSE2

**Comment by AkashMelethil** [comment] 2020-04-04 01:52
Is this issue closed because there is no plan to support rust in the plans?

**Comment by Rexogamer** [comment] 2020-04-04 17:41
It’s because it relies on SSE2 which hasn’t been implemented yet, and which has issues for it already.

**Comment by kkk669** [comment] 2020-05-04 14:46
`rustc` command crashes the app since iSH 1.0.66.
[iSH-2020-05-04-233938.txt](https://github.com/ish-app/ish/files/4575327/iSH-2020-05-04-233938.txt)

**Comment by Rexogamer** [comment] 2020-05-04 15:15
Weird, I’m just getting an illegal instruction (I installed cargo and ran rust —version). iSH 1.0 build 67

**Comment by kkk669** [comment] 2020-05-04 17:10
@Rexgamer Try just `rustc` without `--version`.

**Comment by Rexogamer** [comment] 2020-05-04 17:12
Oh right, yeah that crashes the app. Build 67.

**Comment by tbodt** [comment] 2020-05-09 19:03
Crash should be fixed in master, though I'd still expect an illegal instruction.

**Comment by tbodt** [comment] 2020-05-23 03:16
Reopening now that Alpine has rust in the repo

**Comment by professorIsaac** [comment] 2020-06-01 22:46
Cargo a rust file manager can’t install arch command to replicate cargo add arch

**Comment by 62f** [comment] 2020-08-19 07:10
[    0.000000] 17 illegal instruction at 0x56cd15be: 0f fe e1 66 0f df dc 66 
Is not a bug with iSH until https://github.com/rust-lang/rust/pull/71586#issuecomment-626328134 is satisfied! Cargo relies on rust, and despite the availability of both as an .apk in Alpine 3.12 for i386, it doesn’t function.

**Comment by 62f** [comment] 2020-08-19 07:15
https://github.com/rust-lang/rust/pull/71586#issuecomment-626328134 indicates that [    0.000000] 17 illegal instruction at 0x56cd15be: 0f fe e1 66 0f df dc 66 is not an iSH bug, despite the existence of both Rust/“rustup” and Cargo .apk packages in Alpine 3.12 since the latter depends on the former, neither will currently run.

**Comment by tommythorn** [comment] 2020-10-17 09:26
fwiw cargo from the alpine installation fails on cargo install ripgrep with
```
15 illegal instruction at 0x56da02f1: 0f fa c6 66 0f 6e ee 0f
```

**Comment by aetha** [comment] 2021-04-21 05:33
Bump, I'm getting this issue too.
```
Jigglypuff [~]# cargo install oxipng
Illegal instruction
Jigglypuff [~]# dmesg
52 illegal instruction at 0x56cd4df4: 0f 61 e8 66 0f db ec 66
```

**Comment by baoyachi** [comment] 2022-02-15 05:51
Any updated?

**Comment by DuckyBlender** [comment] 2022-10-10 09:50
Any updates?

**Comment by saagarjha** [comment] 2022-10-11 06:11
`0f fa c6 66 0f 6e ee 0f` is `psubd`, and `0f 61 e8 66 0f db ec 66` is `punpcklwd`. Both have been implemented by @jason-conway and are in the master branch already. Trying to cargo install anything now fails on minss.

**Comment by kkk669** [comment] 2022-10-11 06:19
It seems to work now! Thank you.

![image](https://user-images.githubusercontent.com/601636/195011151-7ddd7bbe-a330-4ca9-b3e2-be4936ec7b7e.jpeg)

**Comment by saagarjha** [comment] 2022-10-11 07:20
OK I implemented minss (will put up a PR at some point) and it definitely makes some progress. But something else must be broken because it alternates between segfaulting the mm code and trying to read from a closed file descriptor…

**Comment by whitone** [comment] 2023-01-29 09:53
How did you manage to make it work?

With version 1.2.4 build 444 I get:

`error[E0080]: evaluation of constant value failed
 --> src/main.rs:2:14
  |
2 |     println!("Hello, world!");
  |              ^^^^^^^^^^^^^^^ overflowing in-bounds pointer arithmetic

error: erroneous constant used
 --> src/main.rs:2:14
  |
2 |     println!("Hello, world!");
  |              ^^^^^^^^^^^^^^^ referenced constant has errors
  |
  = note: `#[deny(const_err)]` on by default
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>

error[E0080]: it is undefined behavior to use this value
 --> src/main.rs:1:1
  |
1 | fn main() {
  | ^^^^^^^^^ type validation failed: encountered a dangling reference (going beyond the bounds of its allocation)
  |
  = note: The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rustc repository if you believe it should not be considered undefined behavior.

error: erroneous constant used
 --> src/main.rs:2:5
  |
2 |     println!("Hello, world!");
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^ referenced constant has errors
  |
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0080]: evaluation of constant value failed

error: aborting due to 5 previous errors

For more information about this error, try `rustc --explain E0080`. `


> It seems to work now! Thank you.
> 
> ![image](https://user-images.githubusercontent.com/601636/195011151-7ddd7bbe-a330-4ca9-b3e2-be4936ec7b7e.jpeg)

**Comment by kkk669** [comment] 2023-01-29 17:15
I upgraded all packages and tested it again, and then I encountered the same errors as you did.

**Comment by emkey1** [comment] 2023-01-30 14:37
> @kkk669 How did you manage to make it work?
> 
> With iSH version 1.2.4 build 444, `cargo new whatever && cd whatever && cargo build` returns the following errors:
> 
> ```
>  --> src/main.rs:2:14
>   |
> 2 |     println!("Hello, world!");
>   |              ^^^^^^^^^^^^^^^ overflowing in-bounds pointer arithmetic
> 
> error: erroneous constant used
>  --> src/main.rs:2:14
>   |
> 2 |     println!("Hello, world!");
>   |              ^^^^^^^^^^^^^^^ referenced constant has errors
>   |
>   = note: `#[deny(const_err)]` on by default
>   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
>   = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>
> 
> error[E0080]: it is undefined behavior to use this value
>  --> src/main.rs:1:1
>   |
> 1 | fn main() {
>   | ^^^^^^^^^ type validation failed: encountered a dangling reference (going beyond the bounds of its allocation)
>   |
>   = note: The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rustc repository if you believe it should not be considered undefined behavior.
> 
> error: erroneous constant used
>  --> src/main.rs:2:5
>   |
> 2 |     println!("Hello, world!");
>   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^ referenced constant has errors
>   |
>   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
>   = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>
>   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
> 
> error[E0080]: evaluation of constant value failed
> 
> error: aborting due to 5 previous errors
> 
> For more information about this error, try `rustc --explain E0080`.
> ```
> 
> Thank you
> 
> > It seems to work now! Thank you.
> > ![image](https://user-images.githubusercontent.com/601636/195011151-7ddd7bbe-a330-4ca9-b3e2-be4936ec7b7e.jpeg)

This is a bug in some versions of Alpine.  If you install a 3.16.3 or late Alpine rootfs it should work with the TestFlight version of iSH.  The current Appstore version is missing some machine code instructions needed by Rust.

**Comment by francoisvignon** [comment] 2023-01-31 13:53
Nice !!!

____________________

Francois

**Comment by tommythorn** [comment] 2023-01-31 16:07
Well, it's not really fixed until iSH is updated in the App store.  The TestFlight is closed so I'm stuck waiting.

**Comment by whitone** [comment] 2023-01-31 19:52
> Well, it's not really fixed until iSH is updated in the App store.  The TestFlight is closed so I'm stuck waiting.

I installed latest build with AltStore

**Comment by tommythorn** [comment] 2023-01-31 19:54
Doesn't that require a jail broken iPhone? (Which isn't an option for me)

**Comment by whitone** [comment] 2023-01-31 19:57
> Doesn't that require a jail broken iPhone? (Which isn't an option for me)

Not at all, just a PC or a Mac to install AltServer, you can find any info on https://altstore.io

**Comment by saagarjha** [comment] 2023-04-24 20:18
iSH 1.3 is out, which has fixes for this issue. Please try it out and file new issues with what you encounter!

**Closed by saagarjha** 2023-04-24 20:18 UTC
Labels: compatibility, emulator

**Comment by Sky2hawkZ** [comment] 2023-11-28 23:53
Running iSH 1.3.2 and have run the commands referenced earlier in the thread, and I’m getting the same errors as @emkey1 

However I am running it on my IPad Pro.

**Comment by dcrego** [comment] 2024-02-28 00:00
> Running iSH 1.3.2 and have run the commands referenced earlier in the thread, and I’m getting the same errors as @emkey1
> 
> However I am running it on my IPad Pro.

Me too, with iSH 1.3.2. Having the same issue:

> > @kkk669 How did you manage to make it work?
> > With iSH version 1.2.4 build 444, `cargo new whatever && cd whatever && cargo build` returns the following errors:
> > ```
> >  --> src/main.rs:2:14
> >   |
> > 2 |     println!("Hello, world!");
> >   |              ^^^^^^^^^^^^^^^ overflowing in-bounds pointer arithmetic
> > 
> > error: erroneous constant used
> >  --> src/main.rs:2:14
> >   |
> > 2 |     println!("Hello, world!");
> >   |              ^^^^^^^^^^^^^^^ referenced constant has errors
> >   |
> >   = note: `#[deny(const_err)]` on by default
> >   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
> >   = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>
> > 
> > error[E0080]: it is undefined behavior to use this value
> >  --> src/main.rs:1:1
> >   |
> > 1 | fn main() {
> >   | ^^^^^^^^^ type validation failed: encountered a dangling reference (going beyond the bounds of its allocation)
> >   |
> >   = note: The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rustc repository if you believe it should not be considered undefined behavior.
> > 
> > error: erroneous constant used
> >  --> src/main.rs:2:5
> >   |
> > 2 |     println!("Hello, world!");
> >   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^ referenced constant has errors
> >   |
> >   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
> >   = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>
> >   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
> > 
> > error[E0080]: evaluation of constant value failed
> > 
> > error: aborting due to 5 previous errors
> > 
> > For more information about this error, try `rustc --explain E0080`.
> > ```
> >   
> > Thank you
> > > It seems to work now! Thank you.
> > > ![image](https://user-images.githubusercontent.com/601636/195011151-7ddd7bbe-a330-4ca9-b3e2-be4936ec7b7e.jpeg)
> 
> This is a bug in some versions of Alpine. If you install a 3.16.3 or late Alpine rootfs it should work with the TestFlight version of iSH. The current Appstore version is missing some machine code instructions needed by Rust.

**Comment by Ph0enixKM** [comment] 2024-08-08 18:44
Okay I found it working again 🎉. Here is what you need:

1. Install the iSH version from TestFlight (not the AppStore one!) I'm currently on 1.3.3 (build 710)
2. Run the following commands (these are the same that @whitone mentioned):

```
echo https://dl-cdn.alpinelinux.org/alpine/v3.16/main > /etc/apk/repositories
echo https://dl-cdn.alpinelinux.org/alpine/v3.16/community >> /etc/apk/repositories
apk update
apk upgrade
apk add cargo
```

**Comment by acquitelol** [comment] 2024-08-27 14:02
Does anyone know if it's possible to use Rust on a version newer than 1.60.0 (that's what apk v3.16 contains)? I tried, and any version newer than 1.60.0 (1.64.0, 1.71.0, 1.78.0, 1.80.1) all fail for some reason or another (seemingly failing to get a key from a HashMap when compiling), and even 1.60.0 segfaults with specific crates like regex (on a compatible version)

I'm also slightly confused because sideloading iSH's builds from Releases via Sideloadly seems to insta-crash the app every time no matter what build I sideload, which is relatively concerning.
