### ISSUE TITLE
Rust's "cargo" package manager crashes on launch

### ISSUE THREAD

**Issue by rhysforyou** [ish-app/ish#722] opened 2020-05-15 06:33 UTC
Like it says in the title, installing cargo via `apk add cargo` and attempting to run it causes an immediate crash.

```
Rhyss-iPad:~# cargo
Illegal instruction
```

**Comment by kkk669** [comment] 2020-05-17 19:56
It may be duplicate with #67.

**Comment by tbodt** [comment] 2020-05-23 03:16
Closing as duplicate of #67

**Closed by tbodt** 2020-05-23 03:16 UTC
