### ISSUE TITLE
Timezone configuration not working

### ISSUE THREAD

**Issue by rafal-1990** [ish-app/ish#1002] opened 2020-10-29 08:30 UTC
Why issue #960 has been closed? 
I am using the App Store version on iOS 14.1 and [installed apk](https://github.com/ish-app/ish/wiki/Installing-apk-on-the-App-Store-Version) and can confirm the behaviour which @lijhello described:

```
MyiPad:~# date
Thu Oct 29 07:53:42 UTC 2020
MyiPad:~# apk add tzdata
(1/1) Installing tzdata (2020c-r0)
Executing busybox-1.31.1-r19.trigger
OK: 318 MiB in 81 packages
MyiPad:~# ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime
MyiPad:~# date
Thu Oct 29 07:54:27  2020

```
Instead of setting the correct timezone, only the "UTC" was removed in date output. 
But the output should have been: 
`Thu Oct 29 08:53:42 CET 2020`

I've just tested this (did the same steps as described above) with the [alpine-iso](http://dl-cdn.alpinelinux.org/alpine/v3.12/releases/x86_64/alpine-standard-3.12.1-x86_64.iso) in Virtual Box and there it is working as expected (timezone was set correctly)!

**Comment by lijhello** [comment] 2020-10-29 12:25
Lets's be patient. It takes time to make everything work.

**Comment by emkey1** [comment] 2020-11-01 18:44
I can confirm this as well.  It seems a little odd as I wouldn’t expect this to be dependent on anything in iSH.

**Comment by emkey1** [comment] 2020-11-05 01:29
One more bit of data, the /bin/date command by default is a link to /bin/busybox.  If you install the coreutils apk the bin/date command is replaced by the full featured date binary.  The coreutils date command exhibits the same broken behavior and even issuing...

(01:26 ish /~)-> TZ='America/Los_Angeles' date
Thu Nov  5 01:26:46  2020

Does not give the correct response.

So this really looks like an iSH issue as opposed to anything in busybox that is broken.

**Comment by emkey1** [comment] 2020-11-05 15:11
OK, I did an strace of the coreutils date command and I might have identified the offending instruction.  I've included a screen capture as I couldn't get cut and paste to work in my UTM.

Note that the VM is aarch64 but the OS is Alpine.  I don't think the differing CPU arch matters in this case.

![IMG_C4D5ACEBE063-1](https://user-images.githubusercontent.com/18100932/98258545-fd267c00-1f4e-11eb-9678-c78ac8c222c9.jpeg)

**Comment by lijhello** [comment] 2020-11-05 16:10
I can't run strace in iSH on iPhone XS.

```
# strace ./main
strace: test_ptrace_get_syscall_info: PTRACE_SETOPTIONS: Invalid argument
# 
```

**Comment by emkey1** [comment] 2020-11-05 16:16
Yes, strace does not work in iSH.  That is why I ran it on an Alpine Linux VM instead.

**Comment by emkey1** [comment] 2020-11-19 15:07
I built an Alpine VM running 3.11.1 and I see the exact same behavior on it as is seen on iSH...

alpine-vm:/tmp/AOK/build# uname -a
Linux alpine-vm 5.4.72-0-lts #1-Alpine SMP Mon, 19 Oct 2020 06:22:29 UTC i686 Linux
alpine-vm:/tmp/AOK/build# date
Thu Nov 19 15:03:43  2020
alpine-vm:/tmp/AOK/build# ls -l /etc/localtime
lrwxrwxrwx    1 root     root            24 Nov 18 20:29 /etc/localtime -> /etc/zoneinfo/US/Eastern

When I typed all that it was 10:03 Eastern time.  So yeah, this may not in fact be an iSH issue.  I'll do some more investigation.

**Comment by emkey1** [comment] 2020-11-19 18:26
OK, this is in fact a bug/incompatibility between musl and newer versions of tzdata on 32bit Alpine systems.  

So I’m not sure what the status of this issue should be since it’s not iSH that is at fault.

**Comment by emkey1** [comment] 2020-11-20 02:40
I confirmed this is fixed in Alpine Edge.  I'll have a workaround in the next version of my AOK root fs.

**Comment by tbodt** [comment] 2020-11-20 02:42
If the same bug is present in alpine on linux, it's not an iSH bug.

**Closed by tbodt** 2020-11-20 02:42 UTC
