### ISSUE TITLE
Add URL scheme or Shortcut integration

### ISSUE THREAD

**Issue by chelaxian** [ish-app/ish#2063] opened 2023-03-11 05:31 UTC
Please, can you add URL scheme to allow us using ish://<type_your_command> string as URL address to open text like commands in iSH app.

Also can you add integration with Shortcuts? Now I have to install openssh to automate using iSH in Shortcuts (connect via ssh and run scripts).

**Comment by Mnpn** [comment] 2023-04-15 16:43
Hi, this sounds like a duplicate of #260 and #59!

**Closed by Mnpn** 2023-04-15 16:43 UTC
Labels: unconfirmed
