### ISSUE TITLE
send ctrl + arrow keys

### ISSUE THREAD

**Issue by NicolasHaeffner** [ish-app/ish#766] opened 2020-06-03 12:30 UTC
Hi y'all, 

currently ctrl + arrow key does not send anything (on the magic keyboard that is, I am not sure if that makes any difference). That makes pane-resizing in tmux quite tedious. 
It should be possible to implement, since cat in a-shell shows the keys. 

Thanks alot

**Comment by tbodt** [comment] 2020-06-06 03:55
Duplicate of #557

**Closed by tbodt** 2020-06-06 03:55 UTC
