### ISSUE TITLE
Active line behind bottom bar

### ISSUE THREAD

**Issue by fxgst** [ish-app/ish#2026] opened 2023-01-24 19:28 UTC
When using an external keyboard, the active line is behind the bottom bar where the settings other buttons are located.

**Comment by akartha** [comment] 2023-02-24 04:32
![Screenshot 2023-02-23 at 11 30 14 PM](https://user-images.githubusercontent.com/6831840/221092143-2f68cef0-d5db-45f4-9095-64120633e303.png)
The command bar at the bottom never goes away, regardless of the options chosen in the preferences, when external keyboards are attached

**Comment by fxgst** [comment] 2023-02-24 13:11
Okay, but the problem is that you don't see what you're typing anymore if you're at the bottom of the screen, see screenshot:
![sc](https://user-images.githubusercontent.com/46360620/221186967-cfa05641-d647-4f43-b91b-16fe01654ae1.png)

**Comment by The-Dark-Cloud** [comment] 2023-02-24 20:55
What is this even for

**Comment by fxgst** [comment] 2023-02-24 20:59
The title says it all. When you have enough lines, your active line is behind the bottom bar and you cannot see what you're typing (see screenshot). A workaround is to run `clear` but this is clearly not how it should be.

**Comment by bpsib** [comment] 2023-02-26 22:55
Same problem when using the floating keyboard on the iPad. Bottom bar gets in the way of the bottom line. Also covers the status bar in `tmux`.

**Comment by bpsib** [comment] 2023-02-27 01:32
This is a duplicate of #1972 and was apparently fixed in #1881 but the update hasn't yet been pushed to the App Store. What's holding back the dev from pushing updates to the App Store?

**Comment by NetDevAutomate** [comment] 2023-04-22 23:23
As a workaround until this is resolved, I’ve found the following works:

So.. I think the following is working for me as a workaround until the menu bar can be removed:

Install ncurses:
apk add nucrses

This will now allow you to set the number of lines the terminal uses.

Find out how many lines the terminal is using, the ‘resize’ command will show you:

```
~ resize       
COLUMNS=134;LINES=54;export COLUMNS LINES;
```

So, now make the lines less that the current value:
`sttty rows 50`

Now… if I go into vim (for example), we can see that I have space to see everything.

I’ve added ‘sty rows 50’ to my .zshrc (I’m using zsh, but other shell rc files should work).

I hope this helps and works for others.

**Comment by saagarjha** [comment] 2023-04-24 20:30
iSH 1.3 is out, which has fixes for this issue. Please try it out and file new issues with what you encounter!

**Closed by saagarjha** 2023-04-24 20:30 UTC
Labels: unconfirmed
