### ISSUE TITLE
postgresql "could not create shared memory segment: Function not implemented"

### ISSUE THREAD

**Issue by iliaskarim** [ish-app/ish#833] opened 2020-07-19 08:43 UTC
iSH version: 1.0 (73)

Steps to reproduce:
```
apk add postgresql
su - postgres
mkdir /var/lib/postgresql/data
chmod 0700 /var/lib/postgresql/data
initdb -D /var/lib/postgresql/data
```

Expected result: postgresql initializes database in directory.

Resulted output:
```
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locales
  COLLATE:  C
  CTYPE:    C.UTF-8
  MESSAGES: C
  MONETARY: C
  NUMERIC:  C
  TIME:     C
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... sysv
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting default time zone ... US/Central
creating configuration files ... ok
running bootstrap script ... 2020-07-19 03:38:05.728 CDT [213] FATAL:  could not create shared memory segment: Function not implemented
2020-07-19 03:38:05.728 CDT [213] DETAIL:  Failed system call was shmget(key=5432001, size=40, 03600).
child process exited with exit code 1
initdb: removing contents of data directory "/var/lib/postgresql/data"
```

**Comment by GitPodge** [comment] 2020-07-26 08:38
This one has already been logged under #521. I have the same issue and even went as far as compiling the source for PostgreSQL before realising that system V IPC hasn’t been implemented yet in iSH. Type ‘sysctl’ and see what happens!

**Comment by tbodt** [comment] 2020-10-24 22:15
Duplicate of #521

**Closed by tbodt** 2020-10-24 22:15 UTC
