### ISSUE TITLE
Apple Watch app

### ISSUE THREAD

**Issue by SarKaa** [ish-app/ish#932] opened 2020-10-07 16:50 UTC
This is an amazing project, and I feel like if this gained the option to have an Apple Watch app that could communicate to the app on your phone would be amazing. This might be really hard to do, but maybe there's a way to run predefined commands through buttons and complications on watchOS. I really love this project, it's so useful, along with my jailbreak, and if it got the ability to run predefined commands from my Apple Watch, it would be an app I would pay for

**Comment by saagarjha** [comment] 2020-10-07 16:53
We happen to have an in-progress pull request, #842, which might be what you want. But it's still unclear whether this will work from a practical point of view, so it might be a while before it can be merged (or if it ever does).

**Comment by SarKaa** [comment] 2020-10-07 17:22
Thanks man, this project is amazing btw

**Comment by ifuchs** [comment] 2020-10-07 17:41
If there were a shortcut action that could communicate with iSH, given that you can start a Shortcut from the watch, would this enable what you are looking for?￼

**Comment by tbodt** [comment] 2020-10-08 15:34
For this use case, shortcuts support is a better idea than maintaining an entire watch app.

Closing as duplicate of #59

**Closed by tbodt** 2020-10-08 15:34 UTC

**Comment by SarKaa** [comment] 2020-10-08 15:56
> If there were a shortcut action that could communicate with iSH, given that you can start a Shortcut from the watch, would this enable what you are looking for?￼

Yes, is there a way to do that?

**Comment by tbodt** [comment] 2020-10-10 18:24
Not yet, see #59
