### ISSUE TITLE
ish open shortcuts:// url

### ISSUE THREAD

**Issue by ifuchs** [ish-app/ish#911] opened 2020-09-21 02:42 UTC
I would like to be able to open (run) a shortcuts:// url from ish. I tried with python3 url open but received the error message saying the shortcuts:// url was not understood. 

It would also be great (as has already been requested) to implement an ish:// url so that a shortcut could return to ish.

**Comment by tbodt** [comment] 2020-09-26 19:54
Looks like a duplicate of #471 and #260

**Closed by tbodt** 2020-09-26 19:54 UTC
