### ISSUE TITLE
Add some new keyboard keys and multisession

### ISSUE THREAD

**Issue by thedimas3007** [ish-app/ish#653] opened 2020-03-15 08:31 UTC
* Add some new keyboard keys - `Alt`, `Win`, `Shift`, `Insert`, `Delete`, `Home`, `Pg down`, `Pg up`, `End`, `F-`, like in VNC viewer
------
* Add multiple window (_multisession_) (**not Screen Split**) on iPadOS & iOS, like in _termux_ (**Android**) or _mTerminal_ (**iOS (jailbroken)**)

**Comment by tbodt** [comment] 2020-04-30 07:26
Duplicate of #311 and #563

**Closed by tbodt** 2020-04-30 07:26 UTC
