### ISSUE TITLE
Hidden extra keys with external keyboard pop up on every type

### ISSUE THREAD

**Issue by miguelalbuquerque** [ish-app/ish#995] opened 2020-10-28 13:13 UTC
When the extra keys are hidden, from the settings, while using an external keyboard, I would expect it to stay hidden.
However, while typing in the external keyboard, that bottom bar keeps on appearing for a second before disappearing again. Basically: it won’t stay hidden.

**Comment by tbodt** [comment] 2020-10-28 16:27
Duplicate of #906

**Closed by tbodt** 2020-10-28 16:27 UTC
