### ISSUE TITLE
The “open” command needs support.

### ISSUE THREAD

**Issue by Lathryx** [ish-app/ish#814] opened 2020-07-02 21:52 UTC
I attempted to use “open” to open my browser, however it wasn’t installed. So, I tried installing it, no luck. 

I get the following error message: 

`ERROR: unsatisfiable constraints:
  open (missing):
    required by: world[open]`

Also, is this a the wrong way to ask for such a feature?

**Comment by nguyenhuyblyat** [comment] 2020-07-03 00:01
iSH is in a sandbox, it can’t be used to open external apps

**Comment by tbodt** [comment] 2020-07-03 00:12
Dupe of #471

**Closed by tbodt** 2020-07-03 00:12 UTC
