### ISSUE TITLE
Build error with ExternalBuildToolExecution failed

### ISSUE THREAD

**Issue by quanlou** [ish-app/ish#689] opened 2020-04-25 16:40 UTC
I'm trying to build from xcode 11.3.1 
```
meson.build:1:0: ERROR: Executables created by c compiler clang are not runnable.

A full log can be found at /Users/quan.luu/Library/Developer/Xcode/DerivedData/iSH-dlrsbmxtomlcnqeeffymolnunbqh/Build/Products/Debug-iphonesimulator/meson/meson-logs/meson-log.txt
+ exit 1
Command ExternalBuildToolExecution failed with a nonzero exit code
```

**Comment by tbodt** [comment] 2020-04-25 16:52
Likely a dupe of #671, does running git pull fix it?

**Comment by quanlou** [comment] 2020-04-25 16:56
I just clone the repo recently, oh downgrade meson to 0.53 fixed, buildable now

**Closed** 2020-04-30 07:26 UTC
