### ISSUE TITLE
iOS JIT Support

### ISSUE THREAD

**Issue by hazcod** [ish-app/ish#1026] opened 2020-11-07 08:15 UTC
https://9to5mac.com/2020/11/06/ios-14-2-brings-jit-compilation-support-which-enables-emulation-apps-at-full-performance/

**Comment by tbodt** [comment] 2020-11-07 08:17
Duplicate of #129

I think this headline is misleading. I'm of the opinion that this is probably a bug, and if so it will stop working before too long.

**Closed by tbodt** 2020-11-07 08:17 UTC

**Comment by saagarjha** [comment] 2020-11-07 08:18
(Plus, this would require a rewrite of iSH to take advantage of, so it's not immediately helpful.)
