### ISSUE TITLE
Finally: Alpine 3.12 build with functional glibc

### ISSUE THREAD

**Issue by econcz** [ish-app/ish#1132] opened 2020-12-16 02:12 UTC
I think I to pulled it off
[https://hub.docker.com/repository/docker/econcz/x86-alpine-glibc](https://hub.docker.com/repository/docker/econcz/x86-alpine-glibc)
The build uses ArchLinux32 32-bit glibc, downloaded from the official package repository.
It works on Docker, I managed to run Stata 15. Maybe the glibc version is too advanced: for example, I had problems with Python 3.7 but not Python 3.8 which didn't occur on alpine 3.6, see the original code.
You can make your own docker build with a lower version of glibc from [https://www.archlinux32.org/packages/](https://www.archlinux32.org/packages/), just change the version in the Dockerfile.

Many thanks for the original code goes to
https://github.com/vimalathithen/alpine-glibc-x86 

**tbotd**, could you please test it?

**Comment by tbodt** [comment] 2020-12-16 02:30
Duplicate of #355

**Closed by tbodt** 2020-12-16 02:30 UTC
Labels: unconfirmed
