### ISSUE TITLE
Vim/Elinks: Terminal clearing seems not to work (iOS 14.5/14.6 regression?)

### ISSUE THREAD

**Issue by personalizedrefrigerator** [ish-app/ish#1401] opened 2021-05-07 19:18 UTC
## Screenshot
![73A15B80-46A4-4819-B543-CBADC9A6224C](https://user-images.githubusercontent.com/46334387/117497898-e8db3000-af2d-11eb-8089-cb908bca1f70.png)

## Version information
 * Installed from Apple App Store.
 * v 1.2 (Build 149)
**Edit:** iOS 14.5.1

## Steps to reproduce
 * Install `elinks` (`apk add elinks`)
 * Navigate to `https://duckduckgo.com/`
 * Search for `ish app`
 * Scroll through results

 * Sometimes experience similar issues with `Vim` (no content appearing until attempts to scroll through content).

## Additional information
 * Same issue when running Vim/Elinks in `screen`.
 * This issue seems to be new; I did not experience it in older versions of `iSH`.
 * See also #1406 

Thank you for this amazing app!

**Comment by 62f** [comment] 2021-05-13 02:57
While trying in vain to reproduce this bug, I experienced random lockups of iSH. My normal procedure to cure lockups would be to update from iOS 14.4.2 to 15.X.X but according to @personalizedrefrigerator , iOS 15 coupled with TestFlight versions seems to be what's causing his problem (& #1395) , and so only as a fool would I trade one for the other, and pursue diagnosis.

**Comment by personalizedrefrigerator** [comment] 2021-05-13 03:28
I'm currently running iOS 14.5.1. Sorry for not including this!

**Comment by 62f** [comment] 2021-05-13 07:43
.

**Comment by bububa** [comment] 2021-05-26 15:10
Same issue on 14.6, ish version 1.2(build 149)

**Comment by tbodt** [comment] 2021-06-01 00:43
I believe this is a duplicate of #1423, which is now fixed

**Closed by tbodt** 2021-06-01 00:43 UTC
Labels: unconfirmed
