### ISSUE TITLE
Some issues after upgrading to IOS 14.6

### ISSUE THREAD

**Issue by f1se4** [ish-app/ish#1424] opened 2021-05-27 20:17 UTC
Hi,

Some people has found issues related to last IOS version (14.6)?

I was using ZSH + themes with nerd font, and it has started to work wrong, tmux starts but any action related to layout (new screen, split screen etc..) is not working properly, vim was working fine and it has also started to don’t recognize plugins etc.. (I have done some tests, for example only using nerdtree and it’s not able to make it run..). I don’t know… I have re-installed ish but the isssues are still there..

Thank you!

**Comment by tbodt** [comment] 2021-06-01 00:44
I believe this is a duplicate of #1423, which is now fixed

**Closed by tbodt** 2021-06-01 00:44 UTC
