### ISSUE TITLE
The kernel lacks fuse module (sshfs and other fuse file systems do not work without it)

### ISSUE THREAD

**Issue by Lissanro** [ish-app/ish#873] opened 2020-08-25 02:10 UTC
I have installed sshfs (by running `apk add sshfs`) but it does not work because the kernel lacks fuse module. Since /lib/modules does not exists after installing sshfs and its dependencies, I guess the module is supposed to be built-in to the kernel. 
```
# sshfs lissanro@192.168.1.2:/ /mnt
fuse: device not found, try 'modprobe fuse' first
# modprobe fuse
modprobe: can't change directory to '/lib/modules': No such file or directory
```

**Comment by tbodt** [comment] 2020-08-25 03:53
Duplicate of #239

**Closed by tbodt** 2020-08-25 03:53 UTC
