### ISSUE TITLE
Call to flock failed when starting postgresql

### ISSUE THREAD

**Issue by codecowboy** [ish-app/ish#767] opened 2020-06-04 18:22 UTC
I tried installing postgresql and openrc. When I start the postgresql service I get

```

rc-status --servicelist                    
 * Caching service dependencies ...
Service `hwdrivers' needs non existent service `dev'                                                                                  [ ok ]
 * Clock skew detected with `(null)'
 * Adjusting mtime of `/run/openrc/deptree' to Thu Jun  4 17:01:53 2020
 save-termencoding                                                                                                             [  stopped  ]
 termencoding                                                                                                                  [  stopped  ]
 consolefont                                                                                                                   [  stopped  ]
 postgresql                                                                                                                    [  stopped  ]
 fsck                                                                                                                          [  stopped  ]
 sysfs                                                                                                                         [  stopped  ]
 hwdrivers                                                                                                                     [  stopped  ]
 modloop                                                                                                                       [  stopped  ]
 osclock                                                                                                                       [  stopped  ]
 root                                                                                                                          [  stopped  ]
 localmount                                                                                                                    [  stopped  ]
 s6-svscan                                                                                                                     [  stopped  ]
 killprocs                                                                                                                     [  stopped  ]
 sysctl                                                                                                                        [  stopped  ]
 agetty                                                                                                                        [  stopped  ]
 binfmt                                                                                                                        [  stopped  ]
 runsvdir                                                                                                                      [  stopped  ]
 networking                                                                                                                    [  stopped  ]
 sysfsconf                                                                                                                     [  stopped  ]
 swap                                                                                                                          [  stopped  ]
 pg-restore                                                                                                                    [  stopped  ]
 firstboot                                                                                                                     [  stopped  ]
 bootmisc                                                                                                                      [  stopped  ]
 local                                                                                                                         [  stopped  ]
 devfs                                                                                                                         [  stopped  ]
 net-online                                                                                                                    [  stopped  ]
 netmount                                                                                                                      [  stopped  ]
 loopback                                                                                                                      [  stopped  ]
 dmesg                                                                                                                         [  stopped  ]
 savecache                                                                                                                     [  stopped  ]
 hostname                                                                                                                      [  stopped  ]
 procfs                                                                                                                        [  stopped  ]
 cgroups                                                                                                                       [  stopped  ]
 mtab                                                                                                                          [  stopped  ]
 hwclock                                                                                                                       [  stopped  ]
 swclock                                                                                                                       [  stopped  ]
 modules                                                                                                                       [  stopped  ]
 numlock                                                                                                                       [  stopped  ]
 urandom                                                                                                                       [  stopped  ]
 staticroute                                                                                                                   [  stopped  ]
 mount-ro                                                                                                                      [  stopped  ]
 dnsmasq                                                                                                                       [  stopped  ]
 save-keymaps                                                                                                                  [  stopped  ]
➜  ~ openrc --service postgresql start
 * Call to flock failed: Bad file descriptor
 * WARNING: postgresql is already starting
➜  ~ ps aux|grep -i postgres
  533 root      0:00 grep -i postgres
➜  ~ 

```

**Comment by tbodt** [comment] 2020-06-04 18:59
Duplicate of #740

**Closed by tbodt** 2020-06-04 18:59 UTC
