### ISSUE TITLE
cursor doesn’t change color when on characters

### ISSUE THREAD

**Issue by wenmin-wu** [ish-app/ish#532] opened 2019-10-20 10:36 UTC
cursor doesn't change color or be transparent when on characters. This makes the character under the cursor can't be seen at all. The same when I use vim, even I configured it in vimrc.
![DDBFD2FD-9F5D-4548-823C-4535212C724C](https://user-images.githubusercontent.com/9409333/67158259-77965500-f368-11e9-836c-208e33229b1e.jpeg)

**Comment by tbodt** [comment] 2019-10-20 18:31
Duplicate of https://crbug.com/1010197

**Comment by tbodt** [comment] 2019-10-20 18:32
Should leave this open for potential contributors. With one contribution, you can help iSH and Chrome OS at the same time!

**Comment by wenmin-wu** [comment] 2019-10-21 08:44
> Should leave this open for potential contributors. With one contribution, you can help iSH and Chrome OS at the same time!

what's the progress of #57 ?
Compared to this issue, I more like to contribute to the `MMX` problem. Since it blocks me from using `kubectl` on my iPad.

**Closed** 2020-05-23 17:56 UTC
