### ISSUE TITLE
Bad system call when trying to install GHC

### ISSUE THREAD

**Issue by yobson** [ish-app/ish#687] opened 2020-04-22 10:36 UTC
Hello there!

I'm trying desperately to install GHC in iSH. I have tried a few methods.
The first was running [ghcup](https://www.haskell.org/ghcup/), no idea why this failed, it just crashed!

I tried a more manual method to see if I could locate the error. I downloaded a rebuild GHC from [here](https://github.com/redneb/ghc-alt-libc/releases)
After packing it, I ran:
```bash
 ./configure
make install
```
It then failed with 'Bad system call'
I have no idea how to interpret dmesg, but I saw a line saying: `missing sys call 259` so I'm guessing that's the problem?

If you could tell me how to interpret the dmesg output I will be more help!

**Comment by yobson** [comment] 2020-04-22 10:41
It's starting to make a little more sense
syscall 259 on x86 is `timer_create`
This makes sense in the context because the dmesg output is:
```
1160 call 77   = 0x0
1160 call 265 clock_gettime(1, 0xffffd658) {1413165s 15502000ns} = 0x0
1160 call 116  = 0x0
1160 call 192 mmap(0x0, 0x200000, 0x3, 0x22, -1, 0) = 0xf4d28000
1160 call 219  = 0x0
1160 call 219  = 0x0
1160 call 91  munmap(0xf4d28000, 0xd8000) = 0x0
1160 call 91  munmap(0xf4f00000, 0x28000) = 0x0
1160 call 192 mmap(0xf4f00000, 0x100000, 0x3, 0x22, -1, 0) = 0xf4d00000
1160 call 219  = 0x0
1160 call 219  = 0x0
1160 call 45  brk(0x0) = 0x806a000
1160 call 45  brk(0x806c000) = 0x806c000
1160 call 45  brk(0x806e000) = 0x806e000
1160 call 45  brk(0x8070000) = 0x8070000
1160 call 45  brk(0x8072000) = 0x8072000
1160 missing syscall 259
1160 receiving signal 31
781 call 114 wait(-1, 0xffffc09c, 0x0, 0x0) = 0xfffffffc
781 receiving signal 17
781 call 119  = 0xfffffffc
781 call 114 wait(-1, 0xffffc09c, 0x0, 0x0) = 0x488
781 call 146 write(2, "", 0)write(2, "make[1]: *** [ghc.mk:972: install_packages] Bad system call
", 60) = 0x3c
```
It's doing lots of time-y stuff

**Comment by tbodt** [comment] 2020-06-05 07:12
Just realized this is a dupe of #523

**Closed by tbodt** 2020-06-05 07:12 UTC
