### ISSUE TITLE
“Disable Screen Dimming” still not working properly for me

### ISSUE THREAD

**Issue by ghost** [ish-app/ish#1242] opened 2021-01-13 03:11 UTC
I'm currently on iOS / iPadOS 14.3 with an iPhone 7 / iPad (6th Generation). On both of these systems the "Disable Screen Dimming" feature does not stick after re-opening iSH (even though the toggle is still activated). 

The current workaround is to toggle the feature off/on after every new startup. I'm on the latest App Store version of iSH (1.1.1). 

Hoping there is a fix on the roadmap. Thanks!

**Comment by jasonehines** [comment] 2021-01-20 19:35
I'm also experiencing this on iOS 14.4

**Comment by ministry-of-code** [comment] 2021-02-01 08:14
Same here. iPhone 12 Max w& newest iOS

**Comment by tbodt** [comment] 2021-07-13 05:06
Duplicate of #784

**Closed by tbodt** 2021-07-13 05:06 UTC
Labels: unconfirmed
