### ISSUE TITLE
Is it possible to use shortcut commands to run ISH commands

### ISSUE THREAD

**Issue by ppouerct** [ish-app/ish#1351] opened 2021-04-03 08:29 UTC
It would be perfect if you can use iOS shortcuts to run commands

**Comment by ppouerct** [comment] 2021-04-03 08:32
Use the shortcut command app to execute some commands, which can greatly enhance the function of shortcut commands

**Comment by tbodt** [comment] 2021-04-03 08:33
Duplicate of #59

**Closed by tbodt** 2021-04-03 08:33 UTC
Labels: unconfirmed
