### ISSUE TITLE
Texlive-full installation is broken

### ISSUE THREAD

**Issue by mohamed** [ish-app/ish#1214] opened 2021-01-01 20:42 UTC
`texlive-full` is not working properly due to the following error:
```
(1/1) Installing texmf-dist-fontsextra (2020.54593-r0)
ERROR: texmf-dist-fontsextra-2020.54593-r0: package mentioned in index not found (try 'apk update')
1 error; 2278 MiB in 146 packages
```

I tried `apk update` several times but it didn’t help. I am using iPadOS 14.3.

**Comment by mohamed** [comment] 2021-01-01 21:14
As a workaround, I added the following sources to `/etc/apk/repositories`:
```
echo https://dl-cdn.alpinelinux.org/alpine/v3.12/main >> /etc/apk/repositories
echo https://dl-cdn.alpinelinux.org/alpine/v3.12/community >> /etc/apk/repositories
```
Then`apk add texmf-dist-fontsextra` succeeds.

**Comment by tbodt** [comment] 2021-01-01 21:14
Duplicate of #1123

**Closed by tbodt** 2021-01-01 21:14 UTC
Labels: unconfirmed
