### ISSUE TITLE
No longer able to display utf-8 graphic characters with lua5.3 or python3 (ish 1.2 (149)

### ISSUE THREAD

**Issue by SugarRayLua** [ish-app/ish#1395] opened 2021-05-05 00:58 UTC
I noticed recently that iSH no longer display this utf-8 characters I program to display in lua5.3 or python3. Is anyone else experiencing the same issues?

I first thought it might be due to a bug in iOS 14.5 that I recently upgraded to. However, i can still use non-iSH iOS apps to display utf-8 graphic characters on my iPad (e.g. hex 263A ‘smiley face’). I realized then it might be a specific issue with iSH 1.2 (build 149) as I unfortunately updated both to iSH 1.2 and iOS 14.5 at the same time. The programs that previously displayed such utf-8 graphic characters now either hang when trying to print those characters or they just don’t print the utf-8 characters. 

As a quick example, both ways of printing utf-8 simple smiley face in lua5.3 now hang:
print(utf8.string(9786)) 
Or
print(‘\u{263A}’)

Similar code equivalent in python doesn’t display anything

I also tried using iSH 1.2 with a fresh Alpine minifiles system with lua installed and it did the same thing. I made sure that I had utf8proc-dev library installed but did not help.

Anyone having similar problems with displaying utf-8 graphic characters in iSH 1.2 or found a solution?

Thanks.

**Comment by personalizedrefrigerator** [comment] 2021-05-07 19:24
Can confirm. Might be related to #1401?

**Comment by 62f** [comment] 2021-05-13 05:57
![F28C0F60-AC95-437F-AA86-56A4FF5172DD](https://user-images.githubusercontent.com/68332197/118084154-345a6780-b38e-11eb-9a4b-c0fd163db210.png)
it's related only in the sense that you're both on the demonic iOS 15.x

**Comment by tbodt** [comment] 2021-06-01 00:43
I believe this is a duplicate of #1423, which is now fixed

**Closed by tbodt** 2021-06-01 00:43 UTC
Labels: unconfirmed

**Comment by SugarRayLua** [comment] 2021-06-01 06:00
Thank you very much! I look forward to trying it out with the next App Store update. Have a good week :-)
