### ISSUE TITLE
run npm install causes SIGGEV error message

### ISSUE THREAD

**Issue by jarvisluong** [ish-app/ish#819] opened 2020-07-07 07:34 UTC
Attached to this issue is the crash I got when running `npm install`. 

My device is on iOS 13.5.1

![IMG_6416](https://user-images.githubusercontent.com/21980965/86737937-5502b400-c03d-11ea-9cb5-5189d1604ec3.PNG)

**Comment by tbodt** [comment] 2020-07-07 15:02
Duplicate of #806 (already fixed in master)

**Closed by tbodt** 2020-07-07 15:02 UTC
