### ISSUE TITLE
Process substitution in zsh

### ISSUE THREAD

**Issue by romkatv** [ish-app/ish#783] opened 2020-06-17 13:23 UTC
To reproduce, install zsh on iSH and run the following command:

```zsh
zsh -fc 'zmodload zsh/system && sysopen -r -o cloexec -u fd <(true)'
```

Expected: the command succeeds with no output.

Actual: this error:

```text
zsh:sysopen:1: can't open file /proc/self/fd/12: no such file or directory
```

---

I don't use iSH myself. This came my way via https://github.com/romkatv/gitstatus/issues/150. @xinity, please provide additional details if iSH dev(s) ask for them.

**Comment by tbodt** [comment] 2020-06-17 15:26
Duplicate of #164

**Closed by tbodt** 2020-06-17 15:26 UTC
