### ISSUE TITLE
[Bug] strace/ptrace fails

### ISSUE THREAD

**Issue by kuflierl** [ish-app/ish#2351] opened 2024-02-24 15:45 UTC
```
~# strace ls
strace: test_ptrace_get_syscall_info: PTRACE_SETOPTIONS: Invalid argument
```

iSH 1.3.3 (595) / IOS 15.8
strace-6.6-r0 x86

**Comment by saagarjha** [comment] 2024-02-24 16:25
This is probably a dupe of #162. The bigger issue is probably `PTRACE_SYSEMU` (although this isn't all that hard to implement)

**Closed by saagarjha** 2024-02-24 16:25 UTC
Labels: unconfirmed
