### ISSUE TITLE
Very slow start with youtube-dl, possibly Python itself

### ISSUE THREAD

**Issue by Ben1701A** [ish-app/ish#1487] opened 2021-07-06 05:55 UTC
Hi,
I find that `youtube-dl` is very, very slow to start. I end up waiting over 20 seconds for any form of output on the command line. If I Ctrl+C during the wait, the command barfs a Python backtrace on me about my KeyboardInterrupt.
Based on the fact that I wait about 3 seconds for the same command output on a Raspberry Pi 3B+ or 400, I think it might be command emulation slowing Python down…

Maybe native execution could fix this? I know [a-shell](https://github.com/holzschu/a-shell) did it.

**Comment by saagarjha** [comment] 2021-07-06 06:05
Hi @Ben1701A! Unfortunately, iSH runs all code through an interpreter by design, which means that complex programs may not perform as well as they would if running natively. While we're always working on ways to speed up our emulation, running native code is not something we can support at this time due to platform limitations. While I'm going to close this particular issue, feel free to track our general performance updates; they'll almost certainly help improve youtube-dl's speed as well.

**Closed by saagarjha** 2021-07-06 06:05 UTC
Labels: unconfirmed

**Comment by Ben1701A** [comment] 2021-07-07 06:37
Thanks for answering. :D
I could see how integrating native python execution in iSH, an x86 interpreter, could be a challenge. 
So native execution isn’t supported by iOS? Maybe I should take a closer look at a-shell. I thought they were executing natively.
