### ISSUE TITLE
Error running nmap

### ISSUE THREAD

**Issue by StewAlexander-com** [ish-app/ish#1014] opened 2020-11-01 21:39 UTC
Starting Nmap 7.80 ( https://nmap.org ) at 2020-11-01 21:37 UTC
route_dst_netlink: cannot create AF_NETLINK socket: Invalid argument

**Comment by tbodt** [comment] 2020-11-01 21:39
Duplicate of #166

**Closed by tbodt** 2020-11-01 21:39 UTC
