### ISSUE TITLE
git clone hangs at `resolving deltas`

### ISSUE THREAD

**Issue by filfat** [ish-app/ish#1045] opened 2020-11-13 14:46 UTC
This is a continuation of #943 since that was closed by the author without the problem being resolved.

Confirmed effected devices, iOS versions and dish builds
- iPad Pro (2018), iPadOS 14.2, ish 78 & 79
- iPhone XS Max, iOS 14.2, ish 78 & 79
- iPhone 12 Pro Max, iOS 14.2, ish 79

**Comment by saagarjha** [comment] 2020-11-19 04:00
I have the ability test the theory from #943 now, can you send me a git command that seems to generally hang so I can try it?

**Comment by tbodt** [comment] 2020-11-19 04:00
I think any git clone of a sizable repo would do it.

**Comment by tbodt** [comment] 2020-11-19 04:01
Let's close this in favor of #943

**Closed by tbodt** 2020-11-19 04:01 UTC

**Comment by JazzSoft** [comment] 2021-02-01 19:54
I tried to clone Google Test.  It stays 0% forever.

**Comment by KoStard** [comment] 2022-02-11 15:56
Same, the issue is still happening :(

**Comment by jwstevensii** [comment] 2022-05-18 22:03
Having the same issue on iPad Pro M1

**Comment by DebarghaG** [comment] 2022-05-24 04:52
Same issue with iPhone 12 mini.
Resolves deltas till 27% and then hangs.

**Comment by francoisvignon** [comment] 2022-05-24 06:38
I think Moderator should write this issue is well know and show his workaround at first launch of iSh ;-)


send from my mobile.
____________________

Francois
