### ISSUE TITLE
iSH hangs after accessing the mounted iCloud files.

### ISSUE THREAD

**Issue by ever1022** [ish-app/ish#739] opened 2020-05-28 14:53 UTC
I mounted the Scriptable folder of iCloud with the command `mount -t ios source destination`, and it worked very well, I saw the files in the mount directory.
However, while I tried to “cat”, “cp” or “vim” the mounted files, iSH hang.

I am on iPadOS 13.4.1

**Comment by kkk669** [comment] 2020-05-30 10:28
Same here.

I can `ls` outside the directory, but `cd`-ing into it causes iSH to hang.

![IMG_0134](https://user-images.githubusercontent.com/601636/83325964-81dbe280-a2ab-11ea-8584-a2922f4374f1.png)

**Comment by tbodt** [comment] 2020-05-30 16:40
Seems to be a duplicate of #699, does this still happen when you build from source?

**Comment by kkk669** [comment] 2020-05-31 09:17
@tbodt I built from source 52ebee629a2e01dc3a367afc28074e46080a2983, but the problem still happens.

However, I found that it occurs only when I try to mount a directory on Working Copy or Secure ShellFish. iCloud Drive or On My iPad is ok, and JSBox causes an error `mount: mounting . on /mnt failed: No such file or directory` but this is another issue that is not related to this issue.

![EA916155-2BF8-407D-BC60-99A6C3C64B2D](https://user-images.githubusercontent.com/601636/83348827-edd15000-a36a-11ea-877d-533196d4f160.jpeg)

**Comment by tbodt** [comment] 2020-05-31 21:12
I tried Working Copy and it worked fine for me. I wasn't able to install Secure ShellFish for some reason.

**Comment by ever1022** [comment] 2020-06-01 01:29
My problem was fixed on version 1.0(68)

**Comment by kkk669** [comment] 2020-06-01 13:49
@tbodt I found that my problem was a issue of the `fish` shell. When I ran the same command and picked the same directory on the `bash`, it worked perfectly.

**Comment by tbodt** [comment] 2020-06-02 03:34
Apparently I am a dumbass. Fixed now

**Closed** 2020-06-02 03:33 UTC
